package com.dreamhanks.HappyBeautyManager.dto;

import java.util.Date;

public class Customerstamp {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customerstamp.id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customerstamp.owner_phone_number
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String ownerPhoneNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customerstamp.customer_phone_number
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String customerPhoneNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customerstamp.stamp_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer stampId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customerstamp.customer_qr_text
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String customerQrText;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customerstamp.stamp_count
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer stampCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customerstamp.delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Boolean deleteFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customerstamp.validity_start_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Date validityStartDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customerstamp.validity_end_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Date validityEndDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customerstamp.update_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customerstamp.create_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Date createDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customerstamp.id
	 * @return  the value of customerstamp.id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customerstamp.id
	 * @param id  the value for customerstamp.id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customerstamp.owner_phone_number
	 * @return  the value of customerstamp.owner_phone_number
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getOwnerPhoneNumber() {
		return ownerPhoneNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customerstamp.owner_phone_number
	 * @param ownerPhoneNumber  the value for customerstamp.owner_phone_number
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setOwnerPhoneNumber(String ownerPhoneNumber) {
		this.ownerPhoneNumber = ownerPhoneNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customerstamp.customer_phone_number
	 * @return  the value of customerstamp.customer_phone_number
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getCustomerPhoneNumber() {
		return customerPhoneNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customerstamp.customer_phone_number
	 * @param customerPhoneNumber  the value for customerstamp.customer_phone_number
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setCustomerPhoneNumber(String customerPhoneNumber) {
		this.customerPhoneNumber = customerPhoneNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customerstamp.stamp_id
	 * @return  the value of customerstamp.stamp_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getStampId() {
		return stampId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customerstamp.stamp_id
	 * @param stampId  the value for customerstamp.stamp_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setStampId(Integer stampId) {
		this.stampId = stampId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customerstamp.customer_qr_text
	 * @return  the value of customerstamp.customer_qr_text
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getCustomerQrText() {
		return customerQrText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customerstamp.customer_qr_text
	 * @param customerQrText  the value for customerstamp.customer_qr_text
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setCustomerQrText(String customerQrText) {
		this.customerQrText = customerQrText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customerstamp.stamp_count
	 * @return  the value of customerstamp.stamp_count
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getStampCount() {
		return stampCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customerstamp.stamp_count
	 * @param stampCount  the value for customerstamp.stamp_count
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setStampCount(Integer stampCount) {
		this.stampCount = stampCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customerstamp.delete_flg
	 * @return  the value of customerstamp.delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Boolean getDeleteFlg() {
		return deleteFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customerstamp.delete_flg
	 * @param deleteFlg  the value for customerstamp.delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setDeleteFlg(Boolean deleteFlg) {
		this.deleteFlg = deleteFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customerstamp.validity_start_date
	 * @return  the value of customerstamp.validity_start_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Date getValidityStartDate() {
		return validityStartDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customerstamp.validity_start_date
	 * @param validityStartDate  the value for customerstamp.validity_start_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setValidityStartDate(Date validityStartDate) {
		this.validityStartDate = validityStartDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customerstamp.validity_end_date
	 * @return  the value of customerstamp.validity_end_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Date getValidityEndDate() {
		return validityEndDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customerstamp.validity_end_date
	 * @param validityEndDate  the value for customerstamp.validity_end_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setValidityEndDate(Date validityEndDate) {
		this.validityEndDate = validityEndDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customerstamp.update_date
	 * @return  the value of customerstamp.update_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customerstamp.update_date
	 * @param updateDate  the value for customerstamp.update_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customerstamp.create_date
	 * @return  the value of customerstamp.create_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customerstamp.create_date
	 * @param createDate  the value for customerstamp.create_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
}