package com.dreamhanks.HappyBeautyManager.dto;

import java.util.Date;

public class ReservationServicehistory {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_servicehistory.reservation_servicehistory_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer reservationServicehistoryId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_servicehistory.manager_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String managerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_servicehistory.reservation_delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer reservationDeleteFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_servicehistory.judgment_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer judgmentFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_servicehistory.resarvation_create_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Date resarvationCreateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_servicehistory.service_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer serviceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_servicehistory.service_money
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer serviceMoney;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_servicehistory.service_img
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String serviceImg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_servicehistory.customer_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer customerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_servicehistory.owner_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer ownerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_servicehistory.service_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Date serviceDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_servicehistory.delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Boolean deleteFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_servicehistory.service_contents
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String serviceContents;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_servicehistory.reservation_servicehistory_id
	 * @return  the value of reservation_servicehistory.reservation_servicehistory_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getReservationServicehistoryId() {
		return reservationServicehistoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_servicehistory.reservation_servicehistory_id
	 * @param reservationServicehistoryId  the value for reservation_servicehistory.reservation_servicehistory_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setReservationServicehistoryId(Integer reservationServicehistoryId) {
		this.reservationServicehistoryId = reservationServicehistoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_servicehistory.manager_id
	 * @return  the value of reservation_servicehistory.manager_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getManagerId() {
		return managerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_servicehistory.manager_id
	 * @param managerId  the value for reservation_servicehistory.manager_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setManagerId(String managerId) {
		this.managerId = managerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_servicehistory.reservation_delete_flg
	 * @return  the value of reservation_servicehistory.reservation_delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getReservationDeleteFlg() {
		return reservationDeleteFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_servicehistory.reservation_delete_flg
	 * @param reservationDeleteFlg  the value for reservation_servicehistory.reservation_delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setReservationDeleteFlg(Integer reservationDeleteFlg) {
		this.reservationDeleteFlg = reservationDeleteFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_servicehistory.judgment_flg
	 * @return  the value of reservation_servicehistory.judgment_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getJudgmentFlg() {
		return judgmentFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_servicehistory.judgment_flg
	 * @param judgmentFlg  the value for reservation_servicehistory.judgment_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setJudgmentFlg(Integer judgmentFlg) {
		this.judgmentFlg = judgmentFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_servicehistory.resarvation_create_date
	 * @return  the value of reservation_servicehistory.resarvation_create_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Date getResarvationCreateDate() {
		return resarvationCreateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_servicehistory.resarvation_create_date
	 * @param resarvationCreateDate  the value for reservation_servicehistory.resarvation_create_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setResarvationCreateDate(Date resarvationCreateDate) {
		this.resarvationCreateDate = resarvationCreateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_servicehistory.service_id
	 * @return  the value of reservation_servicehistory.service_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getServiceId() {
		return serviceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_servicehistory.service_id
	 * @param serviceId  the value for reservation_servicehistory.service_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setServiceId(Integer serviceId) {
		this.serviceId = serviceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_servicehistory.service_money
	 * @return  the value of reservation_servicehistory.service_money
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getServiceMoney() {
		return serviceMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_servicehistory.service_money
	 * @param serviceMoney  the value for reservation_servicehistory.service_money
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setServiceMoney(Integer serviceMoney) {
		this.serviceMoney = serviceMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_servicehistory.service_img
	 * @return  the value of reservation_servicehistory.service_img
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getServiceImg() {
		return serviceImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_servicehistory.service_img
	 * @param serviceImg  the value for reservation_servicehistory.service_img
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setServiceImg(String serviceImg) {
		this.serviceImg = serviceImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_servicehistory.customer_id
	 * @return  the value of reservation_servicehistory.customer_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getCustomerId() {
		return customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_servicehistory.customer_id
	 * @param customerId  the value for reservation_servicehistory.customer_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_servicehistory.owner_id
	 * @return  the value of reservation_servicehistory.owner_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getOwnerId() {
		return ownerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_servicehistory.owner_id
	 * @param ownerId  the value for reservation_servicehistory.owner_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setOwnerId(Integer ownerId) {
		this.ownerId = ownerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_servicehistory.service_date
	 * @return  the value of reservation_servicehistory.service_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Date getServiceDate() {
		return serviceDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_servicehistory.service_date
	 * @param serviceDate  the value for reservation_servicehistory.service_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setServiceDate(Date serviceDate) {
		this.serviceDate = serviceDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_servicehistory.delete_flg
	 * @return  the value of reservation_servicehistory.delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Boolean getDeleteFlg() {
		return deleteFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_servicehistory.delete_flg
	 * @param deleteFlg  the value for reservation_servicehistory.delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setDeleteFlg(Boolean deleteFlg) {
		this.deleteFlg = deleteFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_servicehistory.service_contents
	 * @return  the value of reservation_servicehistory.service_contents
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getServiceContents() {
		return serviceContents;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_servicehistory.service_contents
	 * @param serviceContents  the value for reservation_servicehistory.service_contents
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setServiceContents(String serviceContents) {
		this.serviceContents = serviceContents;
	}
}