package com.dreamhanks.HappyBeautyManager.dto;

import java.util.Date;

public class ReservationCustomer {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_customer.reservation_customer_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer reservationCustomerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_customer.manager_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String managerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_customer.reservation_delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer reservationDeleteFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_customer.judgment_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer judgmentFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_customer.resarvation_create_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Date resarvationCreateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_customer.customer_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer customerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_customer.customer_name
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String customerName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_customer.customer_img
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String customerImg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_customer.customer_phone_number
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String customerPhoneNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_customer.customer_birth
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String customerBirth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_customer.customer_city
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer customerCity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_customer.customer_town
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer customerTown;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_customer.owner_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer ownerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_customer.customer_money
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer customerMoney;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_customer.create_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_customer.delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Boolean deleteFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_customer.customer_memo
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String customerMemo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_customer.reservation_customer_id
	 * @return  the value of reservation_customer.reservation_customer_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getReservationCustomerId() {
		return reservationCustomerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_customer.reservation_customer_id
	 * @param reservationCustomerId  the value for reservation_customer.reservation_customer_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setReservationCustomerId(Integer reservationCustomerId) {
		this.reservationCustomerId = reservationCustomerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_customer.manager_id
	 * @return  the value of reservation_customer.manager_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getManagerId() {
		return managerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_customer.manager_id
	 * @param managerId  the value for reservation_customer.manager_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setManagerId(String managerId) {
		this.managerId = managerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_customer.reservation_delete_flg
	 * @return  the value of reservation_customer.reservation_delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getReservationDeleteFlg() {
		return reservationDeleteFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_customer.reservation_delete_flg
	 * @param reservationDeleteFlg  the value for reservation_customer.reservation_delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setReservationDeleteFlg(Integer reservationDeleteFlg) {
		this.reservationDeleteFlg = reservationDeleteFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_customer.judgment_flg
	 * @return  the value of reservation_customer.judgment_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getJudgmentFlg() {
		return judgmentFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_customer.judgment_flg
	 * @param judgmentFlg  the value for reservation_customer.judgment_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setJudgmentFlg(Integer judgmentFlg) {
		this.judgmentFlg = judgmentFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_customer.resarvation_create_date
	 * @return  the value of reservation_customer.resarvation_create_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Date getResarvationCreateDate() {
		return resarvationCreateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_customer.resarvation_create_date
	 * @param resarvationCreateDate  the value for reservation_customer.resarvation_create_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setResarvationCreateDate(Date resarvationCreateDate) {
		this.resarvationCreateDate = resarvationCreateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_customer.customer_id
	 * @return  the value of reservation_customer.customer_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getCustomerId() {
		return customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_customer.customer_id
	 * @param customerId  the value for reservation_customer.customer_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_customer.customer_name
	 * @return  the value of reservation_customer.customer_name
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getCustomerName() {
		return customerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_customer.customer_name
	 * @param customerName  the value for reservation_customer.customer_name
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_customer.customer_img
	 * @return  the value of reservation_customer.customer_img
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getCustomerImg() {
		return customerImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_customer.customer_img
	 * @param customerImg  the value for reservation_customer.customer_img
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setCustomerImg(String customerImg) {
		this.customerImg = customerImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_customer.customer_phone_number
	 * @return  the value of reservation_customer.customer_phone_number
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getCustomerPhoneNumber() {
		return customerPhoneNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_customer.customer_phone_number
	 * @param customerPhoneNumber  the value for reservation_customer.customer_phone_number
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setCustomerPhoneNumber(String customerPhoneNumber) {
		this.customerPhoneNumber = customerPhoneNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_customer.customer_birth
	 * @return  the value of reservation_customer.customer_birth
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getCustomerBirth() {
		return customerBirth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_customer.customer_birth
	 * @param customerBirth  the value for reservation_customer.customer_birth
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setCustomerBirth(String customerBirth) {
		this.customerBirth = customerBirth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_customer.customer_city
	 * @return  the value of reservation_customer.customer_city
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getCustomerCity() {
		return customerCity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_customer.customer_city
	 * @param customerCity  the value for reservation_customer.customer_city
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setCustomerCity(Integer customerCity) {
		this.customerCity = customerCity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_customer.customer_town
	 * @return  the value of reservation_customer.customer_town
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getCustomerTown() {
		return customerTown;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_customer.customer_town
	 * @param customerTown  the value for reservation_customer.customer_town
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setCustomerTown(Integer customerTown) {
		this.customerTown = customerTown;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_customer.owner_id
	 * @return  the value of reservation_customer.owner_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getOwnerId() {
		return ownerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_customer.owner_id
	 * @param ownerId  the value for reservation_customer.owner_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setOwnerId(Integer ownerId) {
		this.ownerId = ownerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_customer.customer_money
	 * @return  the value of reservation_customer.customer_money
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getCustomerMoney() {
		return customerMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_customer.customer_money
	 * @param customerMoney  the value for reservation_customer.customer_money
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setCustomerMoney(Integer customerMoney) {
		this.customerMoney = customerMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_customer.create_date
	 * @return  the value of reservation_customer.create_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_customer.create_date
	 * @param createDate  the value for reservation_customer.create_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_customer.delete_flg
	 * @return  the value of reservation_customer.delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Boolean getDeleteFlg() {
		return deleteFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_customer.delete_flg
	 * @param deleteFlg  the value for reservation_customer.delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setDeleteFlg(Boolean deleteFlg) {
		this.deleteFlg = deleteFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_customer.customer_memo
	 * @return  the value of reservation_customer.customer_memo
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getCustomerMemo() {
		return customerMemo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_customer.customer_memo
	 * @param customerMemo  the value for reservation_customer.customer_memo
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setCustomerMemo(String customerMemo) {
		this.customerMemo = customerMemo;
	}
}