package com.dreamhanks.HappyBeautyManager.dto;

import java.util.Date;

public class ReservationReservationhistory {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_reservationhistory.reservation_reservationhistory_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer reservationReservationhistoryId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_reservationhistory.manager_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String managerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_reservationhistory.reservation_delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer reservationDeleteFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_reservationhistory.judgment_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer judgmentFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_reservationhistory.resarvation_create_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Date resarvationCreateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_reservationhistory.reservation_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer reservationId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_reservationhistory.customer_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer customerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_reservationhistory.owner_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer ownerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_reservationhistory.reservation_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String reservationDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_reservationhistory.reservation_time
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String reservationTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_reservationhistory.service_estimated_time
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String serviceEstimatedTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_reservationhistory.delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Boolean deleteFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_reservationhistory.customer_phone_number
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String customerPhoneNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_reservationhistory.reservation_contents
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String reservationContents;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_reservationhistory.reservation_reservationhistory_id
	 * @return  the value of reservation_reservationhistory.reservation_reservationhistory_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getReservationReservationhistoryId() {
		return reservationReservationhistoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_reservationhistory.reservation_reservationhistory_id
	 * @param reservationReservationhistoryId  the value for reservation_reservationhistory.reservation_reservationhistory_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setReservationReservationhistoryId(Integer reservationReservationhistoryId) {
		this.reservationReservationhistoryId = reservationReservationhistoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_reservationhistory.manager_id
	 * @return  the value of reservation_reservationhistory.manager_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getManagerId() {
		return managerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_reservationhistory.manager_id
	 * @param managerId  the value for reservation_reservationhistory.manager_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setManagerId(String managerId) {
		this.managerId = managerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_reservationhistory.reservation_delete_flg
	 * @return  the value of reservation_reservationhistory.reservation_delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getReservationDeleteFlg() {
		return reservationDeleteFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_reservationhistory.reservation_delete_flg
	 * @param reservationDeleteFlg  the value for reservation_reservationhistory.reservation_delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setReservationDeleteFlg(Integer reservationDeleteFlg) {
		this.reservationDeleteFlg = reservationDeleteFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_reservationhistory.judgment_flg
	 * @return  the value of reservation_reservationhistory.judgment_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getJudgmentFlg() {
		return judgmentFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_reservationhistory.judgment_flg
	 * @param judgmentFlg  the value for reservation_reservationhistory.judgment_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setJudgmentFlg(Integer judgmentFlg) {
		this.judgmentFlg = judgmentFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_reservationhistory.resarvation_create_date
	 * @return  the value of reservation_reservationhistory.resarvation_create_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Date getResarvationCreateDate() {
		return resarvationCreateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_reservationhistory.resarvation_create_date
	 * @param resarvationCreateDate  the value for reservation_reservationhistory.resarvation_create_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setResarvationCreateDate(Date resarvationCreateDate) {
		this.resarvationCreateDate = resarvationCreateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_reservationhistory.reservation_id
	 * @return  the value of reservation_reservationhistory.reservation_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getReservationId() {
		return reservationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_reservationhistory.reservation_id
	 * @param reservationId  the value for reservation_reservationhistory.reservation_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setReservationId(Integer reservationId) {
		this.reservationId = reservationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_reservationhistory.customer_id
	 * @return  the value of reservation_reservationhistory.customer_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getCustomerId() {
		return customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_reservationhistory.customer_id
	 * @param customerId  the value for reservation_reservationhistory.customer_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_reservationhistory.owner_id
	 * @return  the value of reservation_reservationhistory.owner_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getOwnerId() {
		return ownerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_reservationhistory.owner_id
	 * @param ownerId  the value for reservation_reservationhistory.owner_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setOwnerId(Integer ownerId) {
		this.ownerId = ownerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_reservationhistory.reservation_date
	 * @return  the value of reservation_reservationhistory.reservation_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getReservationDate() {
		return reservationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_reservationhistory.reservation_date
	 * @param reservationDate  the value for reservation_reservationhistory.reservation_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setReservationDate(String reservationDate) {
		this.reservationDate = reservationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_reservationhistory.reservation_time
	 * @return  the value of reservation_reservationhistory.reservation_time
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getReservationTime() {
		return reservationTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_reservationhistory.reservation_time
	 * @param reservationTime  the value for reservation_reservationhistory.reservation_time
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setReservationTime(String reservationTime) {
		this.reservationTime = reservationTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_reservationhistory.service_estimated_time
	 * @return  the value of reservation_reservationhistory.service_estimated_time
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getServiceEstimatedTime() {
		return serviceEstimatedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_reservationhistory.service_estimated_time
	 * @param serviceEstimatedTime  the value for reservation_reservationhistory.service_estimated_time
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setServiceEstimatedTime(String serviceEstimatedTime) {
		this.serviceEstimatedTime = serviceEstimatedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_reservationhistory.delete_flg
	 * @return  the value of reservation_reservationhistory.delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Boolean getDeleteFlg() {
		return deleteFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_reservationhistory.delete_flg
	 * @param deleteFlg  the value for reservation_reservationhistory.delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setDeleteFlg(Boolean deleteFlg) {
		this.deleteFlg = deleteFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_reservationhistory.customer_phone_number
	 * @return  the value of reservation_reservationhistory.customer_phone_number
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getCustomerPhoneNumber() {
		return customerPhoneNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_reservationhistory.customer_phone_number
	 * @param customerPhoneNumber  the value for reservation_reservationhistory.customer_phone_number
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setCustomerPhoneNumber(String customerPhoneNumber) {
		this.customerPhoneNumber = customerPhoneNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_reservationhistory.reservation_contents
	 * @return  the value of reservation_reservationhistory.reservation_contents
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getReservationContents() {
		return reservationContents;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_reservationhistory.reservation_contents
	 * @param reservationContents  the value for reservation_reservationhistory.reservation_contents
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setReservationContents(String reservationContents) {
		this.reservationContents = reservationContents;
	}
}