package com.dreamhanks.HappyBeautyManager.dto;

public class Reservationhistory {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservationhistory.reservation_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer reservationId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservationhistory.customer_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer customerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservationhistory.owner_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer ownerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservationhistory.reservation_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String reservationDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservationhistory.reservation_time
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String reservationTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservationhistory.service_estimated_time
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String serviceEstimatedTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservationhistory.delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer deleteFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservationhistory.customer_phone_number
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String customerPhoneNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservationhistory.reservation_contents
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String reservationContents;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservationhistory.reservation_id
	 * @return  the value of reservationhistory.reservation_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getReservationId() {
		return reservationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservationhistory.reservation_id
	 * @param reservationId  the value for reservationhistory.reservation_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setReservationId(Integer reservationId) {
		this.reservationId = reservationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservationhistory.customer_id
	 * @return  the value of reservationhistory.customer_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getCustomerId() {
		return customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservationhistory.customer_id
	 * @param customerId  the value for reservationhistory.customer_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservationhistory.owner_id
	 * @return  the value of reservationhistory.owner_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getOwnerId() {
		return ownerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservationhistory.owner_id
	 * @param ownerId  the value for reservationhistory.owner_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setOwnerId(Integer ownerId) {
		this.ownerId = ownerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservationhistory.reservation_date
	 * @return  the value of reservationhistory.reservation_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getReservationDate() {
		return reservationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservationhistory.reservation_date
	 * @param reservationDate  the value for reservationhistory.reservation_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setReservationDate(String reservationDate) {
		this.reservationDate = reservationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservationhistory.reservation_time
	 * @return  the value of reservationhistory.reservation_time
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getReservationTime() {
		return reservationTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservationhistory.reservation_time
	 * @param reservationTime  the value for reservationhistory.reservation_time
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setReservationTime(String reservationTime) {
		this.reservationTime = reservationTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservationhistory.service_estimated_time
	 * @return  the value of reservationhistory.service_estimated_time
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getServiceEstimatedTime() {
		return serviceEstimatedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservationhistory.service_estimated_time
	 * @param serviceEstimatedTime  the value for reservationhistory.service_estimated_time
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setServiceEstimatedTime(String serviceEstimatedTime) {
		this.serviceEstimatedTime = serviceEstimatedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservationhistory.delete_flg
	 * @return  the value of reservationhistory.delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getDeleteFlg() {
		return deleteFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservationhistory.delete_flg
	 * @param deleteFlg  the value for reservationhistory.delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setDeleteFlg(Integer deleteFlg) {
		this.deleteFlg = deleteFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservationhistory.customer_phone_number
	 * @return  the value of reservationhistory.customer_phone_number
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getCustomerPhoneNumber() {
		return customerPhoneNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservationhistory.customer_phone_number
	 * @param customerPhoneNumber  the value for reservationhistory.customer_phone_number
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setCustomerPhoneNumber(String customerPhoneNumber) {
		this.customerPhoneNumber = customerPhoneNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservationhistory.reservation_contents
	 * @return  the value of reservationhistory.reservation_contents
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getReservationContents() {
		return reservationContents;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservationhistory.reservation_contents
	 * @param reservationContents  the value for reservationhistory.reservation_contents
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setReservationContents(String reservationContents) {
		this.reservationContents = reservationContents;
	}
}