package com.dreamhanks.HappyBeautyManager.dto;

public class SearchDisplayMaster {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_display_master.id
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_display_master.identification_num
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    private String identificationNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_display_master.available_flg
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    private Boolean availableFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_display_master.table_name
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    private String tableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_display_master.column_name
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    private String columnName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_display_master.id
     *
     * @return the value of search_display_master.id
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_display_master.id
     *
     * @param id the value for search_display_master.id
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_display_master.identification_num
     *
     * @return the value of search_display_master.identification_num
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    public String getIdentificationNum() {
        return identificationNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_display_master.identification_num
     *
     * @param identificationNum the value for search_display_master.identification_num
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    public void setIdentificationNum(String identificationNum) {
        this.identificationNum = identificationNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_display_master.available_flg
     *
     * @return the value of search_display_master.available_flg
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    public Boolean getAvailableFlg() {
        return availableFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_display_master.available_flg
     *
     * @param availableFlg the value for search_display_master.available_flg
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    public void setAvailableFlg(Boolean availableFlg) {
        this.availableFlg = availableFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_display_master.table_name
     *
     * @return the value of search_display_master.table_name
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_display_master.table_name
     *
     * @param tableName the value for search_display_master.table_name
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_display_master.column_name
     *
     * @return the value of search_display_master.column_name
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    public String getColumnName() {
        return columnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_display_master.column_name
     *
     * @param columnName the value for search_display_master.column_name
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    public void setColumnName(String columnName) {
        this.columnName = columnName;
    }
}