package com.dreamhanks.HappyBeautyManager.dto;

import java.util.Date;

public class Servicehistory {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column servicehistory.service_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer serviceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column servicehistory.service_money
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer serviceMoney;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column servicehistory.service_img
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String serviceImg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column servicehistory.customer_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer customerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column servicehistory.owner_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer ownerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column servicehistory.service_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Date serviceDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column servicehistory.service_contents
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String serviceContents;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column servicehistory.service_id
	 * @return  the value of servicehistory.service_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getServiceId() {
		return serviceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column servicehistory.service_id
	 * @param serviceId  the value for servicehistory.service_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setServiceId(Integer serviceId) {
		this.serviceId = serviceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column servicehistory.service_money
	 * @return  the value of servicehistory.service_money
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getServiceMoney() {
		return serviceMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column servicehistory.service_money
	 * @param serviceMoney  the value for servicehistory.service_money
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setServiceMoney(Integer serviceMoney) {
		this.serviceMoney = serviceMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column servicehistory.service_img
	 * @return  the value of servicehistory.service_img
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getServiceImg() {
		return serviceImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column servicehistory.service_img
	 * @param serviceImg  the value for servicehistory.service_img
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setServiceImg(String serviceImg) {
		this.serviceImg = serviceImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column servicehistory.customer_id
	 * @return  the value of servicehistory.customer_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getCustomerId() {
		return customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column servicehistory.customer_id
	 * @param customerId  the value for servicehistory.customer_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column servicehistory.owner_id
	 * @return  the value of servicehistory.owner_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getOwnerId() {
		return ownerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column servicehistory.owner_id
	 * @param ownerId  the value for servicehistory.owner_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setOwnerId(Integer ownerId) {
		this.ownerId = ownerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column servicehistory.service_date
	 * @return  the value of servicehistory.service_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Date getServiceDate() {
		return serviceDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column servicehistory.service_date
	 * @param serviceDate  the value for servicehistory.service_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setServiceDate(Date serviceDate) {
		this.serviceDate = serviceDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column servicehistory.service_contents
	 * @return  the value of servicehistory.service_contents
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getServiceContents() {
		return serviceContents;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column servicehistory.service_contents
	 * @param serviceContents  the value for servicehistory.service_contents
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setServiceContents(String serviceContents) {
		this.serviceContents = serviceContents;
	}
}