package com.dreamhanks.HappyBeautyManager.dao;

import com.dreamhanks.HappyBeautyManager.dto.ReservationStamp;
import com.dreamhanks.HappyBeautyManager.dto.ReservationStampExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReservationStampMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_stamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	long countByExample(ReservationStampExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_stamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int deleteByExample(ReservationStampExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_stamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int deleteByPrimaryKey(Integer reservationStampId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_stamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int insert(ReservationStamp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_stamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int insertSelective(ReservationStamp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_stamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	List<ReservationStamp> selectByExampleWithBLOBs(ReservationStampExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_stamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	List<ReservationStamp> selectByExample(ReservationStampExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_stamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	ReservationStamp selectByPrimaryKey(Integer reservationStampId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_stamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int updateByExampleSelective(@Param("record") ReservationStamp record,
			@Param("example") ReservationStampExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_stamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int updateByExampleWithBLOBs(@Param("record") ReservationStamp record,
			@Param("example") ReservationStampExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_stamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int updateByExample(@Param("record") ReservationStamp record, @Param("example") ReservationStampExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_stamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int updateByPrimaryKeySelective(ReservationStamp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_stamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int updateByPrimaryKeyWithBLOBs(ReservationStamp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_stamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int updateByPrimaryKey(ReservationStamp record);
}