package com.dreamhanks.HappyBeautyManager.dto;

public class TableListDisplayMaster {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_list_display_master.id
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_list_display_master.group_id
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_list_display_master.identification_num
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    private String identificationNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_list_display_master.available_flg
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    private Boolean availableFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_list_display_master.catergory
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    private String catergory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_list_display_master.table_name
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    private String tableName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_list_display_master.id
     *
     * @return the value of table_list_display_master.id
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_list_display_master.id
     *
     * @param id the value for table_list_display_master.id
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_list_display_master.group_id
     *
     * @return the value of table_list_display_master.group_id
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_list_display_master.group_id
     *
     * @param groupId the value for table_list_display_master.group_id
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_list_display_master.identification_num
     *
     * @return the value of table_list_display_master.identification_num
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    public String getIdentificationNum() {
        return identificationNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_list_display_master.identification_num
     *
     * @param identificationNum the value for table_list_display_master.identification_num
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    public void setIdentificationNum(String identificationNum) {
        this.identificationNum = identificationNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_list_display_master.available_flg
     *
     * @return the value of table_list_display_master.available_flg
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    public Boolean getAvailableFlg() {
        return availableFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_list_display_master.available_flg
     *
     * @param availableFlg the value for table_list_display_master.available_flg
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    public void setAvailableFlg(Boolean availableFlg) {
        this.availableFlg = availableFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_list_display_master.catergory
     *
     * @return the value of table_list_display_master.catergory
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    public String getCatergory() {
        return catergory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_list_display_master.catergory
     *
     * @param catergory the value for table_list_display_master.catergory
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    public void setCatergory(String catergory) {
        this.catergory = catergory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_list_display_master.table_name
     *
     * @return the value of table_list_display_master.table_name
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_list_display_master.table_name
     *
     * @param tableName the value for table_list_display_master.table_name
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }
}