package com.dreamhanks.HappyBeautyManager.dao;

import com.dreamhanks.HappyBeautyManager.dto.TableListDisplayMaster;
import com.dreamhanks.HappyBeautyManager.dto.TableListDisplayMasterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TableListDisplayMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_list_display_master
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    long countByExample(TableListDisplayMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_list_display_master
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    int deleteByExample(TableListDisplayMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_list_display_master
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_list_display_master
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    int insert(TableListDisplayMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_list_display_master
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    int insertSelective(TableListDisplayMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_list_display_master
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    List<TableListDisplayMaster> selectByExample(TableListDisplayMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_list_display_master
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    TableListDisplayMaster selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_list_display_master
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    int updateByExampleSelective(@Param("record") TableListDisplayMaster record, @Param("example") TableListDisplayMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_list_display_master
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    int updateByExample(@Param("record") TableListDisplayMaster record, @Param("example") TableListDisplayMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_list_display_master
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    int updateByPrimaryKeySelective(TableListDisplayMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_list_display_master
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    int updateByPrimaryKey(TableListDisplayMaster record);
}