package com.dreamhanks.HappyBeautyManager.dao;

import com.dreamhanks.HappyBeautyManager.dto.ReservationCustomer;
import com.dreamhanks.HappyBeautyManager.dto.ReservationCustomerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReservationCustomerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_customer
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	long countByExample(ReservationCustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_customer
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int deleteByExample(ReservationCustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_customer
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int deleteByPrimaryKey(Integer reservationCustomerId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_customer
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int insert(ReservationCustomer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_customer
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int insertSelective(ReservationCustomer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_customer
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	List<ReservationCustomer> selectByExampleWithBLOBs(ReservationCustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_customer
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	List<ReservationCustomer> selectByExample(ReservationCustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_customer
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	ReservationCustomer selectByPrimaryKey(Integer reservationCustomerId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_customer
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int updateByExampleSelective(@Param("record") ReservationCustomer record,
			@Param("example") ReservationCustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_customer
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int updateByExampleWithBLOBs(@Param("record") ReservationCustomer record,
			@Param("example") ReservationCustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_customer
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int updateByExample(@Param("record") ReservationCustomer record,
			@Param("example") ReservationCustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_customer
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int updateByPrimaryKeySelective(ReservationCustomer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_customer
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int updateByPrimaryKeyWithBLOBs(ReservationCustomer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_customer
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int updateByPrimaryKey(ReservationCustomer record);
}