package com.dreamhanks.HappyBeautyManager.dao;

import com.dreamhanks.HappyBeautyManager.dto.Stampevent;
import com.dreamhanks.HappyBeautyManager.dto.StampeventExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StampeventMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stampevent
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	long countByExample(StampeventExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stampevent
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int deleteByExample(StampeventExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stampevent
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int deleteByPrimaryKey(Integer stampEventId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stampevent
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int insert(Stampevent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stampevent
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int insertSelective(Stampevent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stampevent
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	List<Stampevent> selectByExampleWithBLOBs(StampeventExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stampevent
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	List<Stampevent> selectByExample(StampeventExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stampevent
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	Stampevent selectByPrimaryKey(Integer stampEventId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stampevent
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int updateByExampleSelective(@Param("record") Stampevent record, @Param("example") StampeventExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stampevent
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int updateByExampleWithBLOBs(@Param("record") Stampevent record, @Param("example") StampeventExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stampevent
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int updateByExample(@Param("record") Stampevent record, @Param("example") StampeventExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stampevent
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int updateByPrimaryKeySelective(Stampevent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stampevent
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int updateByPrimaryKeyWithBLOBs(Stampevent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stampevent
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int updateByPrimaryKey(Stampevent record);
}