package com.dreamhanks.HappyBeautyManager.dto;

import java.util.Date;

public class Customer {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.customer_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Short customerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.store_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Byte storeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.first_name
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String firstName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.last_name
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String lastName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.email
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.address_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Short addressId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.active
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Boolean active;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.create_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.last_update
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Date lastUpdate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.customer_id
	 * @return  the value of customer.customer_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Short getCustomerId() {
		return customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.customer_id
	 * @param customerId  the value for customer.customer_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setCustomerId(Short customerId) {
		this.customerId = customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.store_id
	 * @return  the value of customer.store_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Byte getStoreId() {
		return storeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.store_id
	 * @param storeId  the value for customer.store_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setStoreId(Byte storeId) {
		this.storeId = storeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.first_name
	 * @return  the value of customer.first_name
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getFirstName() {
		return firstName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.first_name
	 * @param firstName  the value for customer.first_name
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.last_name
	 * @return  the value of customer.last_name
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getLastName() {
		return lastName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.last_name
	 * @param lastName  the value for customer.last_name
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.email
	 * @return  the value of customer.email
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.email
	 * @param email  the value for customer.email
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.address_id
	 * @return  the value of customer.address_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Short getAddressId() {
		return addressId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.address_id
	 * @param addressId  the value for customer.address_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setAddressId(Short addressId) {
		this.addressId = addressId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.active
	 * @return  the value of customer.active
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Boolean getActive() {
		return active;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.active
	 * @param active  the value for customer.active
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setActive(Boolean active) {
		this.active = active;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.create_date
	 * @return  the value of customer.create_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.create_date
	 * @param createDate  the value for customer.create_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.last_update
	 * @return  the value of customer.last_update
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Date getLastUpdate() {
		return lastUpdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.last_update
	 * @param lastUpdate  the value for customer.last_update
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}
}