package com.dreamhanks.HappyBeautyManager.dao;

import com.dreamhanks.HappyBeautyManager.dto.ReservationServicehistory;
import com.dreamhanks.HappyBeautyManager.dto.ReservationServicehistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReservationServicehistoryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_servicehistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	long countByExample(ReservationServicehistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_servicehistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int deleteByExample(ReservationServicehistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_servicehistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int deleteByPrimaryKey(Integer reservationServicehistoryId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_servicehistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int insert(ReservationServicehistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_servicehistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int insertSelective(ReservationServicehistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_servicehistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	List<ReservationServicehistory> selectByExampleWithBLOBs(ReservationServicehistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_servicehistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	List<ReservationServicehistory> selectByExample(ReservationServicehistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_servicehistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	ReservationServicehistory selectByPrimaryKey(Integer reservationServicehistoryId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_servicehistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int updateByExampleSelective(@Param("record") ReservationServicehistory record,
			@Param("example") ReservationServicehistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_servicehistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int updateByExampleWithBLOBs(@Param("record") ReservationServicehistory record,
			@Param("example") ReservationServicehistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_servicehistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int updateByExample(@Param("record") ReservationServicehistory record,
			@Param("example") ReservationServicehistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_servicehistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int updateByPrimaryKeySelective(ReservationServicehistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_servicehistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int updateByPrimaryKeyWithBLOBs(ReservationServicehistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_servicehistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int updateByPrimaryKey(ReservationServicehistory record);
}