package com.dreamhanks.searchborad.dto;

public class Borad {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column borad.id
	 * @mbg.generated  Fri Oct 02 15:52:36 JST 2020
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column borad.title
	 * @mbg.generated  Fri Oct 02 15:52:36 JST 2020
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column borad.position
	 * @mbg.generated  Fri Oct 02 15:52:36 JST 2020
	 */
	private String position;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column borad.check_flg
	 * @mbg.generated  Fri Oct 02 15:52:36 JST 2020
	 */
	private String checkFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column borad.creat_at
	 * @mbg.generated  Fri Oct 02 15:52:36 JST 2020
	 */
	private String creatAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column borad.id
	 * @return  the value of borad.id
	 * @mbg.generated  Fri Oct 02 15:52:36 JST 2020
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column borad.id
	 * @param id  the value for borad.id
	 * @mbg.generated  Fri Oct 02 15:52:36 JST 2020
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column borad.title
	 * @return  the value of borad.title
	 * @mbg.generated  Fri Oct 02 15:52:36 JST 2020
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column borad.title
	 * @param title  the value for borad.title
	 * @mbg.generated  Fri Oct 02 15:52:36 JST 2020
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column borad.position
	 * @return  the value of borad.position
	 * @mbg.generated  Fri Oct 02 15:52:36 JST 2020
	 */
	public String getPosition() {
		return position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column borad.position
	 * @param position  the value for borad.position
	 * @mbg.generated  Fri Oct 02 15:52:36 JST 2020
	 */
	public void setPosition(String position) {
		this.position = position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column borad.check_flg
	 * @return  the value of borad.check_flg
	 * @mbg.generated  Fri Oct 02 15:52:36 JST 2020
	 */
	public String getCheckFlg() {
		return checkFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column borad.check_flg
	 * @param checkFlg  the value for borad.check_flg
	 * @mbg.generated  Fri Oct 02 15:52:36 JST 2020
	 */
	public void setCheckFlg(String checkFlg) {
		this.checkFlg = checkFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column borad.creat_at
	 * @return  the value of borad.creat_at
	 * @mbg.generated  Fri Oct 02 15:52:36 JST 2020
	 */
	public String getCreatAt() {
		return creatAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column borad.creat_at
	 * @param creatAt  the value for borad.creat_at
	 * @mbg.generated  Fri Oct 02 15:52:36 JST 2020
	 */
	public void setCreatAt(String creatAt) {
		this.creatAt = creatAt;
	}
}