package com.dreamhanks.HappyBeautyManager.dto;

import java.util.Date;

public class Stamp {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stamp.id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stamp.owner_phone_number
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String ownerPhoneNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stamp.stamp_qr_text
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String stampQrText;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stamp.stamp_name
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String stampName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stamp.stamp_row
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer stampRow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stamp.stamp_col
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer stampCol;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stamp.stamp_img
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String stampImg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stamp.stamp_back_img
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String stampBackImg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stamp.validity_start_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Date validityStartDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stamp.validity_end_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Date validityEndDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stamp.validity_plus_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer validityPlusDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stamp.validity_plus_type
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer validityPlusType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stamp.validity_type
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer validityType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stamp.delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Boolean deleteFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stamp.create_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stamp.stamp_theme
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer stampTheme;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stamp.stamp_contents
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String stampContents;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stamp.id
	 * @return  the value of stamp.id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stamp.id
	 * @param id  the value for stamp.id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stamp.owner_phone_number
	 * @return  the value of stamp.owner_phone_number
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getOwnerPhoneNumber() {
		return ownerPhoneNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stamp.owner_phone_number
	 * @param ownerPhoneNumber  the value for stamp.owner_phone_number
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setOwnerPhoneNumber(String ownerPhoneNumber) {
		this.ownerPhoneNumber = ownerPhoneNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stamp.stamp_qr_text
	 * @return  the value of stamp.stamp_qr_text
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getStampQrText() {
		return stampQrText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stamp.stamp_qr_text
	 * @param stampQrText  the value for stamp.stamp_qr_text
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setStampQrText(String stampQrText) {
		this.stampQrText = stampQrText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stamp.stamp_name
	 * @return  the value of stamp.stamp_name
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getStampName() {
		return stampName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stamp.stamp_name
	 * @param stampName  the value for stamp.stamp_name
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setStampName(String stampName) {
		this.stampName = stampName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stamp.stamp_row
	 * @return  the value of stamp.stamp_row
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getStampRow() {
		return stampRow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stamp.stamp_row
	 * @param stampRow  the value for stamp.stamp_row
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setStampRow(Integer stampRow) {
		this.stampRow = stampRow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stamp.stamp_col
	 * @return  the value of stamp.stamp_col
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getStampCol() {
		return stampCol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stamp.stamp_col
	 * @param stampCol  the value for stamp.stamp_col
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setStampCol(Integer stampCol) {
		this.stampCol = stampCol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stamp.stamp_img
	 * @return  the value of stamp.stamp_img
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getStampImg() {
		return stampImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stamp.stamp_img
	 * @param stampImg  the value for stamp.stamp_img
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setStampImg(String stampImg) {
		this.stampImg = stampImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stamp.stamp_back_img
	 * @return  the value of stamp.stamp_back_img
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getStampBackImg() {
		return stampBackImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stamp.stamp_back_img
	 * @param stampBackImg  the value for stamp.stamp_back_img
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setStampBackImg(String stampBackImg) {
		this.stampBackImg = stampBackImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stamp.validity_start_date
	 * @return  the value of stamp.validity_start_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Date getValidityStartDate() {
		return validityStartDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stamp.validity_start_date
	 * @param validityStartDate  the value for stamp.validity_start_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setValidityStartDate(Date validityStartDate) {
		this.validityStartDate = validityStartDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stamp.validity_end_date
	 * @return  the value of stamp.validity_end_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Date getValidityEndDate() {
		return validityEndDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stamp.validity_end_date
	 * @param validityEndDate  the value for stamp.validity_end_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setValidityEndDate(Date validityEndDate) {
		this.validityEndDate = validityEndDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stamp.validity_plus_date
	 * @return  the value of stamp.validity_plus_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getValidityPlusDate() {
		return validityPlusDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stamp.validity_plus_date
	 * @param validityPlusDate  the value for stamp.validity_plus_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setValidityPlusDate(Integer validityPlusDate) {
		this.validityPlusDate = validityPlusDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stamp.validity_plus_type
	 * @return  the value of stamp.validity_plus_type
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getValidityPlusType() {
		return validityPlusType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stamp.validity_plus_type
	 * @param validityPlusType  the value for stamp.validity_plus_type
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setValidityPlusType(Integer validityPlusType) {
		this.validityPlusType = validityPlusType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stamp.validity_type
	 * @return  the value of stamp.validity_type
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getValidityType() {
		return validityType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stamp.validity_type
	 * @param validityType  the value for stamp.validity_type
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setValidityType(Integer validityType) {
		this.validityType = validityType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stamp.delete_flg
	 * @return  the value of stamp.delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Boolean getDeleteFlg() {
		return deleteFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stamp.delete_flg
	 * @param deleteFlg  the value for stamp.delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setDeleteFlg(Boolean deleteFlg) {
		this.deleteFlg = deleteFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stamp.create_date
	 * @return  the value of stamp.create_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stamp.create_date
	 * @param createDate  the value for stamp.create_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stamp.stamp_theme
	 * @return  the value of stamp.stamp_theme
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getStampTheme() {
		return stampTheme;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stamp.stamp_theme
	 * @param stampTheme  the value for stamp.stamp_theme
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setStampTheme(Integer stampTheme) {
		this.stampTheme = stampTheme;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stamp.stamp_contents
	 * @return  the value of stamp.stamp_contents
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getStampContents() {
		return stampContents;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stamp.stamp_contents
	 * @param stampContents  the value for stamp.stamp_contents
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setStampContents(String stampContents) {
		this.stampContents = stampContents;
	}
}