package com.dreamhanks.HappyBeautyManager.dao;

import com.dreamhanks.HappyBeautyManager.dto.ReservationCustomerstamp;
import com.dreamhanks.HappyBeautyManager.dto.ReservationCustomerstampExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReservationCustomerstampMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_customerstamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	long countByExample(ReservationCustomerstampExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_customerstamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int deleteByExample(ReservationCustomerstampExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_customerstamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int deleteByPrimaryKey(Integer reservationCustomerstampId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_customerstamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int insert(ReservationCustomerstamp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_customerstamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int insertSelective(ReservationCustomerstamp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_customerstamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	List<ReservationCustomerstamp> selectByExample(ReservationCustomerstampExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_customerstamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	ReservationCustomerstamp selectByPrimaryKey(Integer reservationCustomerstampId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_customerstamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int updateByExampleSelective(@Param("record") ReservationCustomerstamp record,
			@Param("example") ReservationCustomerstampExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_customerstamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int updateByExample(@Param("record") ReservationCustomerstamp record,
			@Param("example") ReservationCustomerstampExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_customerstamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int updateByPrimaryKeySelective(ReservationCustomerstamp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_customerstamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int updateByPrimaryKey(ReservationCustomerstamp record);
}