package com.dreamhanks.dto;

public class Worktime {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column worktime.id
	 * @mbg.generated  Thu Oct 15 11:34:30 JST 2020
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column worktime.member_id
	 * @mbg.generated  Thu Oct 15 11:34:30 JST 2020
	 */
	private Integer memberId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column worktime.work_date
	 * @mbg.generated  Thu Oct 15 11:34:30 JST 2020
	 */
	private String workDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column worktime.week
	 * @mbg.generated  Thu Oct 15 11:34:30 JST 2020
	 */
	private Integer week;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column worktime.start_time
	 * @mbg.generated  Thu Oct 15 11:34:30 JST 2020
	 */
	private String startTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column worktime.end_time
	 * @mbg.generated  Thu Oct 15 11:34:30 JST 2020
	 */
	private String endTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column worktime.rest_time
	 * @mbg.generated  Thu Oct 15 11:34:30 JST 2020
	 */
	private String restTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column worktime.memo
	 * @mbg.generated  Thu Oct 15 11:34:30 JST 2020
	 */
	private String memo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column worktime.id
	 * @return  the value of worktime.id
	 * @mbg.generated  Thu Oct 15 11:34:30 JST 2020
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column worktime.id
	 * @param id  the value for worktime.id
	 * @mbg.generated  Thu Oct 15 11:34:30 JST 2020
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column worktime.member_id
	 * @return  the value of worktime.member_id
	 * @mbg.generated  Thu Oct 15 11:34:30 JST 2020
	 */
	public Integer getMemberId() {
		return memberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column worktime.member_id
	 * @param memberId  the value for worktime.member_id
	 * @mbg.generated  Thu Oct 15 11:34:30 JST 2020
	 */
	public void setMemberId(Integer memberId) {
		this.memberId = memberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column worktime.work_date
	 * @return  the value of worktime.work_date
	 * @mbg.generated  Thu Oct 15 11:34:30 JST 2020
	 */
	public String getWorkDate() {
		return workDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column worktime.work_date
	 * @param workDate  the value for worktime.work_date
	 * @mbg.generated  Thu Oct 15 11:34:30 JST 2020
	 */
	public void setWorkDate(String workDate) {
		this.workDate = workDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column worktime.week
	 * @return  the value of worktime.week
	 * @mbg.generated  Thu Oct 15 11:34:30 JST 2020
	 */
	public Integer getWeek() {
		return week;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column worktime.week
	 * @param week  the value for worktime.week
	 * @mbg.generated  Thu Oct 15 11:34:30 JST 2020
	 */
	public void setWeek(Integer week) {
		this.week = week;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column worktime.start_time
	 * @return  the value of worktime.start_time
	 * @mbg.generated  Thu Oct 15 11:34:30 JST 2020
	 */
	public String getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column worktime.start_time
	 * @param startTime  the value for worktime.start_time
	 * @mbg.generated  Thu Oct 15 11:34:30 JST 2020
	 */
	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column worktime.end_time
	 * @return  the value of worktime.end_time
	 * @mbg.generated  Thu Oct 15 11:34:30 JST 2020
	 */
	public String getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column worktime.end_time
	 * @param endTime  the value for worktime.end_time
	 * @mbg.generated  Thu Oct 15 11:34:30 JST 2020
	 */
	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column worktime.rest_time
	 * @return  the value of worktime.rest_time
	 * @mbg.generated  Thu Oct 15 11:34:30 JST 2020
	 */
	public String getRestTime() {
		return restTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column worktime.rest_time
	 * @param restTime  the value for worktime.rest_time
	 * @mbg.generated  Thu Oct 15 11:34:30 JST 2020
	 */
	public void setRestTime(String restTime) {
		this.restTime = restTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column worktime.memo
	 * @return  the value of worktime.memo
	 * @mbg.generated  Thu Oct 15 11:34:30 JST 2020
	 */
	public String getMemo() {
		return memo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column worktime.memo
	 * @param memo  the value for worktime.memo
	 * @mbg.generated  Thu Oct 15 11:34:30 JST 2020
	 */
	public void setMemo(String memo) {
		this.memo = memo;
	}
}