package com.dreamhanks.HappyBeautyManager.dto;

public class Stampevent {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stampevent.stamp_event_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer stampEventId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stampevent.stamp_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer stampId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stampevent.event_space
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer eventSpace;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stampevent.delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Boolean deleteFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stampevent.event_contents
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String eventContents;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stampevent.stamp_event_id
	 * @return  the value of stampevent.stamp_event_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getStampEventId() {
		return stampEventId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stampevent.stamp_event_id
	 * @param stampEventId  the value for stampevent.stamp_event_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setStampEventId(Integer stampEventId) {
		this.stampEventId = stampEventId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stampevent.stamp_id
	 * @return  the value of stampevent.stamp_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getStampId() {
		return stampId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stampevent.stamp_id
	 * @param stampId  the value for stampevent.stamp_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setStampId(Integer stampId) {
		this.stampId = stampId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stampevent.event_space
	 * @return  the value of stampevent.event_space
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getEventSpace() {
		return eventSpace;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stampevent.event_space
	 * @param eventSpace  the value for stampevent.event_space
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setEventSpace(Integer eventSpace) {
		this.eventSpace = eventSpace;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stampevent.delete_flg
	 * @return  the value of stampevent.delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Boolean getDeleteFlg() {
		return deleteFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stampevent.delete_flg
	 * @param deleteFlg  the value for stampevent.delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setDeleteFlg(Boolean deleteFlg) {
		this.deleteFlg = deleteFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stampevent.event_contents
	 * @return  the value of stampevent.event_contents
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getEventContents() {
		return eventContents;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stampevent.event_contents
	 * @param eventContents  the value for stampevent.event_contents
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setEventContents(String eventContents) {
		this.eventContents = eventContents;
	}
}