package com.dreamhanks.dao;

import com.dreamhanks.dto.Member;
import com.dreamhanks.dto.MemberExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemberMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbg.generated  Thu Oct 15 11:34:30 JST 2020
	 */
	long countByExample(MemberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbg.generated  Thu Oct 15 11:34:30 JST 2020
	 */
	int deleteByExample(MemberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbg.generated  Thu Oct 15 11:34:30 JST 2020
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbg.generated  Thu Oct 15 11:34:30 JST 2020
	 */
	int insert(Member record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbg.generated  Thu Oct 15 11:34:30 JST 2020
	 */
	int insertSelective(Member record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbg.generated  Thu Oct 15 11:34:30 JST 2020
	 */
	List<Member> selectByExample(MemberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbg.generated  Thu Oct 15 11:34:30 JST 2020
	 */
	Member selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbg.generated  Thu Oct 15 11:34:30 JST 2020
	 */
	int updateByExampleSelective(@Param("record") Member record, @Param("example") MemberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbg.generated  Thu Oct 15 11:34:30 JST 2020
	 */
	int updateByExample(@Param("record") Member record, @Param("example") MemberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbg.generated  Thu Oct 15 11:34:30 JST 2020
	 */
	int updateByPrimaryKeySelective(Member record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbg.generated  Thu Oct 15 11:34:30 JST 2020
	 */
	int updateByPrimaryKey(Member record);
}