package com.dreamhanks.HappyBeautyManager.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ReservationServicehistoryExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table reservation_servicehistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table reservation_servicehistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table reservation_servicehistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_servicehistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public ReservationServicehistoryExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_servicehistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_servicehistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_servicehistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_servicehistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_servicehistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_servicehistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_servicehistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_servicehistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_servicehistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_servicehistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table reservation_servicehistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andReservationServicehistoryIdIsNull() {
			addCriterion("reservation_servicehistory_id is null");
			return (Criteria) this;
		}

		public Criteria andReservationServicehistoryIdIsNotNull() {
			addCriterion("reservation_servicehistory_id is not null");
			return (Criteria) this;
		}

		public Criteria andReservationServicehistoryIdEqualTo(Integer value) {
			addCriterion("reservation_servicehistory_id =", value, "reservationServicehistoryId");
			return (Criteria) this;
		}

		public Criteria andReservationServicehistoryIdNotEqualTo(Integer value) {
			addCriterion("reservation_servicehistory_id <>", value, "reservationServicehistoryId");
			return (Criteria) this;
		}

		public Criteria andReservationServicehistoryIdGreaterThan(Integer value) {
			addCriterion("reservation_servicehistory_id >", value, "reservationServicehistoryId");
			return (Criteria) this;
		}

		public Criteria andReservationServicehistoryIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("reservation_servicehistory_id >=", value, "reservationServicehistoryId");
			return (Criteria) this;
		}

		public Criteria andReservationServicehistoryIdLessThan(Integer value) {
			addCriterion("reservation_servicehistory_id <", value, "reservationServicehistoryId");
			return (Criteria) this;
		}

		public Criteria andReservationServicehistoryIdLessThanOrEqualTo(Integer value) {
			addCriterion("reservation_servicehistory_id <=", value, "reservationServicehistoryId");
			return (Criteria) this;
		}

		public Criteria andReservationServicehistoryIdIn(List<Integer> values) {
			addCriterion("reservation_servicehistory_id in", values, "reservationServicehistoryId");
			return (Criteria) this;
		}

		public Criteria andReservationServicehistoryIdNotIn(List<Integer> values) {
			addCriterion("reservation_servicehistory_id not in", values, "reservationServicehistoryId");
			return (Criteria) this;
		}

		public Criteria andReservationServicehistoryIdBetween(Integer value1, Integer value2) {
			addCriterion("reservation_servicehistory_id between", value1, value2, "reservationServicehistoryId");
			return (Criteria) this;
		}

		public Criteria andReservationServicehistoryIdNotBetween(Integer value1, Integer value2) {
			addCriterion("reservation_servicehistory_id not between", value1, value2, "reservationServicehistoryId");
			return (Criteria) this;
		}

		public Criteria andManagerIdIsNull() {
			addCriterion("manager_id is null");
			return (Criteria) this;
		}

		public Criteria andManagerIdIsNotNull() {
			addCriterion("manager_id is not null");
			return (Criteria) this;
		}

		public Criteria andManagerIdEqualTo(String value) {
			addCriterion("manager_id =", value, "managerId");
			return (Criteria) this;
		}

		public Criteria andManagerIdNotEqualTo(String value) {
			addCriterion("manager_id <>", value, "managerId");
			return (Criteria) this;
		}

		public Criteria andManagerIdGreaterThan(String value) {
			addCriterion("manager_id >", value, "managerId");
			return (Criteria) this;
		}

		public Criteria andManagerIdGreaterThanOrEqualTo(String value) {
			addCriterion("manager_id >=", value, "managerId");
			return (Criteria) this;
		}

		public Criteria andManagerIdLessThan(String value) {
			addCriterion("manager_id <", value, "managerId");
			return (Criteria) this;
		}

		public Criteria andManagerIdLessThanOrEqualTo(String value) {
			addCriterion("manager_id <=", value, "managerId");
			return (Criteria) this;
		}

		public Criteria andManagerIdLike(String value) {
			addCriterion("manager_id like", value, "managerId");
			return (Criteria) this;
		}

		public Criteria andManagerIdNotLike(String value) {
			addCriterion("manager_id not like", value, "managerId");
			return (Criteria) this;
		}

		public Criteria andManagerIdIn(List<String> values) {
			addCriterion("manager_id in", values, "managerId");
			return (Criteria) this;
		}

		public Criteria andManagerIdNotIn(List<String> values) {
			addCriterion("manager_id not in", values, "managerId");
			return (Criteria) this;
		}

		public Criteria andManagerIdBetween(String value1, String value2) {
			addCriterion("manager_id between", value1, value2, "managerId");
			return (Criteria) this;
		}

		public Criteria andManagerIdNotBetween(String value1, String value2) {
			addCriterion("manager_id not between", value1, value2, "managerId");
			return (Criteria) this;
		}

		public Criteria andReservationDeleteFlgIsNull() {
			addCriterion("reservation_delete_flg is null");
			return (Criteria) this;
		}

		public Criteria andReservationDeleteFlgIsNotNull() {
			addCriterion("reservation_delete_flg is not null");
			return (Criteria) this;
		}

		public Criteria andReservationDeleteFlgEqualTo(Integer value) {
			addCriterion("reservation_delete_flg =", value, "reservationDeleteFlg");
			return (Criteria) this;
		}

		public Criteria andReservationDeleteFlgNotEqualTo(Integer value) {
			addCriterion("reservation_delete_flg <>", value, "reservationDeleteFlg");
			return (Criteria) this;
		}

		public Criteria andReservationDeleteFlgGreaterThan(Integer value) {
			addCriterion("reservation_delete_flg >", value, "reservationDeleteFlg");
			return (Criteria) this;
		}

		public Criteria andReservationDeleteFlgGreaterThanOrEqualTo(Integer value) {
			addCriterion("reservation_delete_flg >=", value, "reservationDeleteFlg");
			return (Criteria) this;
		}

		public Criteria andReservationDeleteFlgLessThan(Integer value) {
			addCriterion("reservation_delete_flg <", value, "reservationDeleteFlg");
			return (Criteria) this;
		}

		public Criteria andReservationDeleteFlgLessThanOrEqualTo(Integer value) {
			addCriterion("reservation_delete_flg <=", value, "reservationDeleteFlg");
			return (Criteria) this;
		}

		public Criteria andReservationDeleteFlgIn(List<Integer> values) {
			addCriterion("reservation_delete_flg in", values, "reservationDeleteFlg");
			return (Criteria) this;
		}

		public Criteria andReservationDeleteFlgNotIn(List<Integer> values) {
			addCriterion("reservation_delete_flg not in", values, "reservationDeleteFlg");
			return (Criteria) this;
		}

		public Criteria andReservationDeleteFlgBetween(Integer value1, Integer value2) {
			addCriterion("reservation_delete_flg between", value1, value2, "reservationDeleteFlg");
			return (Criteria) this;
		}

		public Criteria andReservationDeleteFlgNotBetween(Integer value1, Integer value2) {
			addCriterion("reservation_delete_flg not between", value1, value2, "reservationDeleteFlg");
			return (Criteria) this;
		}

		public Criteria andJudgmentFlgIsNull() {
			addCriterion("judgment_flg is null");
			return (Criteria) this;
		}

		public Criteria andJudgmentFlgIsNotNull() {
			addCriterion("judgment_flg is not null");
			return (Criteria) this;
		}

		public Criteria andJudgmentFlgEqualTo(Integer value) {
			addCriterion("judgment_flg =", value, "judgmentFlg");
			return (Criteria) this;
		}

		public Criteria andJudgmentFlgNotEqualTo(Integer value) {
			addCriterion("judgment_flg <>", value, "judgmentFlg");
			return (Criteria) this;
		}

		public Criteria andJudgmentFlgGreaterThan(Integer value) {
			addCriterion("judgment_flg >", value, "judgmentFlg");
			return (Criteria) this;
		}

		public Criteria andJudgmentFlgGreaterThanOrEqualTo(Integer value) {
			addCriterion("judgment_flg >=", value, "judgmentFlg");
			return (Criteria) this;
		}

		public Criteria andJudgmentFlgLessThan(Integer value) {
			addCriterion("judgment_flg <", value, "judgmentFlg");
			return (Criteria) this;
		}

		public Criteria andJudgmentFlgLessThanOrEqualTo(Integer value) {
			addCriterion("judgment_flg <=", value, "judgmentFlg");
			return (Criteria) this;
		}

		public Criteria andJudgmentFlgIn(List<Integer> values) {
			addCriterion("judgment_flg in", values, "judgmentFlg");
			return (Criteria) this;
		}

		public Criteria andJudgmentFlgNotIn(List<Integer> values) {
			addCriterion("judgment_flg not in", values, "judgmentFlg");
			return (Criteria) this;
		}

		public Criteria andJudgmentFlgBetween(Integer value1, Integer value2) {
			addCriterion("judgment_flg between", value1, value2, "judgmentFlg");
			return (Criteria) this;
		}

		public Criteria andJudgmentFlgNotBetween(Integer value1, Integer value2) {
			addCriterion("judgment_flg not between", value1, value2, "judgmentFlg");
			return (Criteria) this;
		}

		public Criteria andResarvationCreateDateIsNull() {
			addCriterion("resarvation_create_date is null");
			return (Criteria) this;
		}

		public Criteria andResarvationCreateDateIsNotNull() {
			addCriterion("resarvation_create_date is not null");
			return (Criteria) this;
		}

		public Criteria andResarvationCreateDateEqualTo(Date value) {
			addCriterion("resarvation_create_date =", value, "resarvationCreateDate");
			return (Criteria) this;
		}

		public Criteria andResarvationCreateDateNotEqualTo(Date value) {
			addCriterion("resarvation_create_date <>", value, "resarvationCreateDate");
			return (Criteria) this;
		}

		public Criteria andResarvationCreateDateGreaterThan(Date value) {
			addCriterion("resarvation_create_date >", value, "resarvationCreateDate");
			return (Criteria) this;
		}

		public Criteria andResarvationCreateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("resarvation_create_date >=", value, "resarvationCreateDate");
			return (Criteria) this;
		}

		public Criteria andResarvationCreateDateLessThan(Date value) {
			addCriterion("resarvation_create_date <", value, "resarvationCreateDate");
			return (Criteria) this;
		}

		public Criteria andResarvationCreateDateLessThanOrEqualTo(Date value) {
			addCriterion("resarvation_create_date <=", value, "resarvationCreateDate");
			return (Criteria) this;
		}

		public Criteria andResarvationCreateDateIn(List<Date> values) {
			addCriterion("resarvation_create_date in", values, "resarvationCreateDate");
			return (Criteria) this;
		}

		public Criteria andResarvationCreateDateNotIn(List<Date> values) {
			addCriterion("resarvation_create_date not in", values, "resarvationCreateDate");
			return (Criteria) this;
		}

		public Criteria andResarvationCreateDateBetween(Date value1, Date value2) {
			addCriterion("resarvation_create_date between", value1, value2, "resarvationCreateDate");
			return (Criteria) this;
		}

		public Criteria andResarvationCreateDateNotBetween(Date value1, Date value2) {
			addCriterion("resarvation_create_date not between", value1, value2, "resarvationCreateDate");
			return (Criteria) this;
		}

		public Criteria andServiceIdIsNull() {
			addCriterion("service_id is null");
			return (Criteria) this;
		}

		public Criteria andServiceIdIsNotNull() {
			addCriterion("service_id is not null");
			return (Criteria) this;
		}

		public Criteria andServiceIdEqualTo(Integer value) {
			addCriterion("service_id =", value, "serviceId");
			return (Criteria) this;
		}

		public Criteria andServiceIdNotEqualTo(Integer value) {
			addCriterion("service_id <>", value, "serviceId");
			return (Criteria) this;
		}

		public Criteria andServiceIdGreaterThan(Integer value) {
			addCriterion("service_id >", value, "serviceId");
			return (Criteria) this;
		}

		public Criteria andServiceIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("service_id >=", value, "serviceId");
			return (Criteria) this;
		}

		public Criteria andServiceIdLessThan(Integer value) {
			addCriterion("service_id <", value, "serviceId");
			return (Criteria) this;
		}

		public Criteria andServiceIdLessThanOrEqualTo(Integer value) {
			addCriterion("service_id <=", value, "serviceId");
			return (Criteria) this;
		}

		public Criteria andServiceIdIn(List<Integer> values) {
			addCriterion("service_id in", values, "serviceId");
			return (Criteria) this;
		}

		public Criteria andServiceIdNotIn(List<Integer> values) {
			addCriterion("service_id not in", values, "serviceId");
			return (Criteria) this;
		}

		public Criteria andServiceIdBetween(Integer value1, Integer value2) {
			addCriterion("service_id between", value1, value2, "serviceId");
			return (Criteria) this;
		}

		public Criteria andServiceIdNotBetween(Integer value1, Integer value2) {
			addCriterion("service_id not between", value1, value2, "serviceId");
			return (Criteria) this;
		}

		public Criteria andServiceMoneyIsNull() {
			addCriterion("service_money is null");
			return (Criteria) this;
		}

		public Criteria andServiceMoneyIsNotNull() {
			addCriterion("service_money is not null");
			return (Criteria) this;
		}

		public Criteria andServiceMoneyEqualTo(Integer value) {
			addCriterion("service_money =", value, "serviceMoney");
			return (Criteria) this;
		}

		public Criteria andServiceMoneyNotEqualTo(Integer value) {
			addCriterion("service_money <>", value, "serviceMoney");
			return (Criteria) this;
		}

		public Criteria andServiceMoneyGreaterThan(Integer value) {
			addCriterion("service_money >", value, "serviceMoney");
			return (Criteria) this;
		}

		public Criteria andServiceMoneyGreaterThanOrEqualTo(Integer value) {
			addCriterion("service_money >=", value, "serviceMoney");
			return (Criteria) this;
		}

		public Criteria andServiceMoneyLessThan(Integer value) {
			addCriterion("service_money <", value, "serviceMoney");
			return (Criteria) this;
		}

		public Criteria andServiceMoneyLessThanOrEqualTo(Integer value) {
			addCriterion("service_money <=", value, "serviceMoney");
			return (Criteria) this;
		}

		public Criteria andServiceMoneyIn(List<Integer> values) {
			addCriterion("service_money in", values, "serviceMoney");
			return (Criteria) this;
		}

		public Criteria andServiceMoneyNotIn(List<Integer> values) {
			addCriterion("service_money not in", values, "serviceMoney");
			return (Criteria) this;
		}

		public Criteria andServiceMoneyBetween(Integer value1, Integer value2) {
			addCriterion("service_money between", value1, value2, "serviceMoney");
			return (Criteria) this;
		}

		public Criteria andServiceMoneyNotBetween(Integer value1, Integer value2) {
			addCriterion("service_money not between", value1, value2, "serviceMoney");
			return (Criteria) this;
		}

		public Criteria andServiceImgIsNull() {
			addCriterion("service_img is null");
			return (Criteria) this;
		}

		public Criteria andServiceImgIsNotNull() {
			addCriterion("service_img is not null");
			return (Criteria) this;
		}

		public Criteria andServiceImgEqualTo(String value) {
			addCriterion("service_img =", value, "serviceImg");
			return (Criteria) this;
		}

		public Criteria andServiceImgNotEqualTo(String value) {
			addCriterion("service_img <>", value, "serviceImg");
			return (Criteria) this;
		}

		public Criteria andServiceImgGreaterThan(String value) {
			addCriterion("service_img >", value, "serviceImg");
			return (Criteria) this;
		}

		public Criteria andServiceImgGreaterThanOrEqualTo(String value) {
			addCriterion("service_img >=", value, "serviceImg");
			return (Criteria) this;
		}

		public Criteria andServiceImgLessThan(String value) {
			addCriterion("service_img <", value, "serviceImg");
			return (Criteria) this;
		}

		public Criteria andServiceImgLessThanOrEqualTo(String value) {
			addCriterion("service_img <=", value, "serviceImg");
			return (Criteria) this;
		}

		public Criteria andServiceImgLike(String value) {
			addCriterion("service_img like", value, "serviceImg");
			return (Criteria) this;
		}

		public Criteria andServiceImgNotLike(String value) {
			addCriterion("service_img not like", value, "serviceImg");
			return (Criteria) this;
		}

		public Criteria andServiceImgIn(List<String> values) {
			addCriterion("service_img in", values, "serviceImg");
			return (Criteria) this;
		}

		public Criteria andServiceImgNotIn(List<String> values) {
			addCriterion("service_img not in", values, "serviceImg");
			return (Criteria) this;
		}

		public Criteria andServiceImgBetween(String value1, String value2) {
			addCriterion("service_img between", value1, value2, "serviceImg");
			return (Criteria) this;
		}

		public Criteria andServiceImgNotBetween(String value1, String value2) {
			addCriterion("service_img not between", value1, value2, "serviceImg");
			return (Criteria) this;
		}

		public Criteria andCustomerIdIsNull() {
			addCriterion("customer_id is null");
			return (Criteria) this;
		}

		public Criteria andCustomerIdIsNotNull() {
			addCriterion("customer_id is not null");
			return (Criteria) this;
		}

		public Criteria andCustomerIdEqualTo(Integer value) {
			addCriterion("customer_id =", value, "customerId");
			return (Criteria) this;
		}

		public Criteria andCustomerIdNotEqualTo(Integer value) {
			addCriterion("customer_id <>", value, "customerId");
			return (Criteria) this;
		}

		public Criteria andCustomerIdGreaterThan(Integer value) {
			addCriterion("customer_id >", value, "customerId");
			return (Criteria) this;
		}

		public Criteria andCustomerIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("customer_id >=", value, "customerId");
			return (Criteria) this;
		}

		public Criteria andCustomerIdLessThan(Integer value) {
			addCriterion("customer_id <", value, "customerId");
			return (Criteria) this;
		}

		public Criteria andCustomerIdLessThanOrEqualTo(Integer value) {
			addCriterion("customer_id <=", value, "customerId");
			return (Criteria) this;
		}

		public Criteria andCustomerIdIn(List<Integer> values) {
			addCriterion("customer_id in", values, "customerId");
			return (Criteria) this;
		}

		public Criteria andCustomerIdNotIn(List<Integer> values) {
			addCriterion("customer_id not in", values, "customerId");
			return (Criteria) this;
		}

		public Criteria andCustomerIdBetween(Integer value1, Integer value2) {
			addCriterion("customer_id between", value1, value2, "customerId");
			return (Criteria) this;
		}

		public Criteria andCustomerIdNotBetween(Integer value1, Integer value2) {
			addCriterion("customer_id not between", value1, value2, "customerId");
			return (Criteria) this;
		}

		public Criteria andOwnerIdIsNull() {
			addCriterion("owner_id is null");
			return (Criteria) this;
		}

		public Criteria andOwnerIdIsNotNull() {
			addCriterion("owner_id is not null");
			return (Criteria) this;
		}

		public Criteria andOwnerIdEqualTo(Integer value) {
			addCriterion("owner_id =", value, "ownerId");
			return (Criteria) this;
		}

		public Criteria andOwnerIdNotEqualTo(Integer value) {
			addCriterion("owner_id <>", value, "ownerId");
			return (Criteria) this;
		}

		public Criteria andOwnerIdGreaterThan(Integer value) {
			addCriterion("owner_id >", value, "ownerId");
			return (Criteria) this;
		}

		public Criteria andOwnerIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("owner_id >=", value, "ownerId");
			return (Criteria) this;
		}

		public Criteria andOwnerIdLessThan(Integer value) {
			addCriterion("owner_id <", value, "ownerId");
			return (Criteria) this;
		}

		public Criteria andOwnerIdLessThanOrEqualTo(Integer value) {
			addCriterion("owner_id <=", value, "ownerId");
			return (Criteria) this;
		}

		public Criteria andOwnerIdIn(List<Integer> values) {
			addCriterion("owner_id in", values, "ownerId");
			return (Criteria) this;
		}

		public Criteria andOwnerIdNotIn(List<Integer> values) {
			addCriterion("owner_id not in", values, "ownerId");
			return (Criteria) this;
		}

		public Criteria andOwnerIdBetween(Integer value1, Integer value2) {
			addCriterion("owner_id between", value1, value2, "ownerId");
			return (Criteria) this;
		}

		public Criteria andOwnerIdNotBetween(Integer value1, Integer value2) {
			addCriterion("owner_id not between", value1, value2, "ownerId");
			return (Criteria) this;
		}

		public Criteria andServiceDateIsNull() {
			addCriterion("service_date is null");
			return (Criteria) this;
		}

		public Criteria andServiceDateIsNotNull() {
			addCriterion("service_date is not null");
			return (Criteria) this;
		}

		public Criteria andServiceDateEqualTo(Date value) {
			addCriterion("service_date =", value, "serviceDate");
			return (Criteria) this;
		}

		public Criteria andServiceDateNotEqualTo(Date value) {
			addCriterion("service_date <>", value, "serviceDate");
			return (Criteria) this;
		}

		public Criteria andServiceDateGreaterThan(Date value) {
			addCriterion("service_date >", value, "serviceDate");
			return (Criteria) this;
		}

		public Criteria andServiceDateGreaterThanOrEqualTo(Date value) {
			addCriterion("service_date >=", value, "serviceDate");
			return (Criteria) this;
		}

		public Criteria andServiceDateLessThan(Date value) {
			addCriterion("service_date <", value, "serviceDate");
			return (Criteria) this;
		}

		public Criteria andServiceDateLessThanOrEqualTo(Date value) {
			addCriterion("service_date <=", value, "serviceDate");
			return (Criteria) this;
		}

		public Criteria andServiceDateIn(List<Date> values) {
			addCriterion("service_date in", values, "serviceDate");
			return (Criteria) this;
		}

		public Criteria andServiceDateNotIn(List<Date> values) {
			addCriterion("service_date not in", values, "serviceDate");
			return (Criteria) this;
		}

		public Criteria andServiceDateBetween(Date value1, Date value2) {
			addCriterion("service_date between", value1, value2, "serviceDate");
			return (Criteria) this;
		}

		public Criteria andServiceDateNotBetween(Date value1, Date value2) {
			addCriterion("service_date not between", value1, value2, "serviceDate");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgIsNull() {
			addCriterion("delete_flg is null");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgIsNotNull() {
			addCriterion("delete_flg is not null");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgEqualTo(Boolean value) {
			addCriterion("delete_flg =", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgNotEqualTo(Boolean value) {
			addCriterion("delete_flg <>", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgGreaterThan(Boolean value) {
			addCriterion("delete_flg >", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgGreaterThanOrEqualTo(Boolean value) {
			addCriterion("delete_flg >=", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgLessThan(Boolean value) {
			addCriterion("delete_flg <", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgLessThanOrEqualTo(Boolean value) {
			addCriterion("delete_flg <=", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgIn(List<Boolean> values) {
			addCriterion("delete_flg in", values, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgNotIn(List<Boolean> values) {
			addCriterion("delete_flg not in", values, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgBetween(Boolean value1, Boolean value2) {
			addCriterion("delete_flg between", value1, value2, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgNotBetween(Boolean value1, Boolean value2) {
			addCriterion("delete_flg not between", value1, value2, "deleteFlg");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table reservation_servicehistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table reservation_servicehistory
     *
     * @mbg.generated do_not_delete_during_merge Mon Nov 16 16:02:40 KST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}