package com.dreamhanks.HappyBeautyManager.dao;

import com.dreamhanks.HappyBeautyManager.dto.Stamp;
import com.dreamhanks.HappyBeautyManager.dto.StampExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StampMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	long countByExample(StampExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int deleteByExample(StampExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int insert(Stamp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int insertSelective(Stamp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	List<Stamp> selectByExampleWithBLOBs(StampExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	List<Stamp> selectByExample(StampExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	Stamp selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int updateByExampleSelective(@Param("record") Stamp record, @Param("example") StampExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int updateByExampleWithBLOBs(@Param("record") Stamp record, @Param("example") StampExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int updateByExample(@Param("record") Stamp record, @Param("example") StampExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int updateByPrimaryKeySelective(Stamp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int updateByPrimaryKeyWithBLOBs(Stamp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int updateByPrimaryKey(Stamp record);
}