package com.dreamhanks.HappyBeautyManager.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ReservationStampExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table reservation_stamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table reservation_stamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table reservation_stamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_stamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public ReservationStampExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_stamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_stamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_stamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_stamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_stamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_stamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_stamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_stamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_stamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_stamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table reservation_stamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andReservationStampIdIsNull() {
			addCriterion("reservation_stamp_id is null");
			return (Criteria) this;
		}

		public Criteria andReservationStampIdIsNotNull() {
			addCriterion("reservation_stamp_id is not null");
			return (Criteria) this;
		}

		public Criteria andReservationStampIdEqualTo(Integer value) {
			addCriterion("reservation_stamp_id =", value, "reservationStampId");
			return (Criteria) this;
		}

		public Criteria andReservationStampIdNotEqualTo(Integer value) {
			addCriterion("reservation_stamp_id <>", value, "reservationStampId");
			return (Criteria) this;
		}

		public Criteria andReservationStampIdGreaterThan(Integer value) {
			addCriterion("reservation_stamp_id >", value, "reservationStampId");
			return (Criteria) this;
		}

		public Criteria andReservationStampIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("reservation_stamp_id >=", value, "reservationStampId");
			return (Criteria) this;
		}

		public Criteria andReservationStampIdLessThan(Integer value) {
			addCriterion("reservation_stamp_id <", value, "reservationStampId");
			return (Criteria) this;
		}

		public Criteria andReservationStampIdLessThanOrEqualTo(Integer value) {
			addCriterion("reservation_stamp_id <=", value, "reservationStampId");
			return (Criteria) this;
		}

		public Criteria andReservationStampIdIn(List<Integer> values) {
			addCriterion("reservation_stamp_id in", values, "reservationStampId");
			return (Criteria) this;
		}

		public Criteria andReservationStampIdNotIn(List<Integer> values) {
			addCriterion("reservation_stamp_id not in", values, "reservationStampId");
			return (Criteria) this;
		}

		public Criteria andReservationStampIdBetween(Integer value1, Integer value2) {
			addCriterion("reservation_stamp_id between", value1, value2, "reservationStampId");
			return (Criteria) this;
		}

		public Criteria andReservationStampIdNotBetween(Integer value1, Integer value2) {
			addCriterion("reservation_stamp_id not between", value1, value2, "reservationStampId");
			return (Criteria) this;
		}

		public Criteria andManagerIdIsNull() {
			addCriterion("manager_id is null");
			return (Criteria) this;
		}

		public Criteria andManagerIdIsNotNull() {
			addCriterion("manager_id is not null");
			return (Criteria) this;
		}

		public Criteria andManagerIdEqualTo(String value) {
			addCriterion("manager_id =", value, "managerId");
			return (Criteria) this;
		}

		public Criteria andManagerIdNotEqualTo(String value) {
			addCriterion("manager_id <>", value, "managerId");
			return (Criteria) this;
		}

		public Criteria andManagerIdGreaterThan(String value) {
			addCriterion("manager_id >", value, "managerId");
			return (Criteria) this;
		}

		public Criteria andManagerIdGreaterThanOrEqualTo(String value) {
			addCriterion("manager_id >=", value, "managerId");
			return (Criteria) this;
		}

		public Criteria andManagerIdLessThan(String value) {
			addCriterion("manager_id <", value, "managerId");
			return (Criteria) this;
		}

		public Criteria andManagerIdLessThanOrEqualTo(String value) {
			addCriterion("manager_id <=", value, "managerId");
			return (Criteria) this;
		}

		public Criteria andManagerIdLike(String value) {
			addCriterion("manager_id like", value, "managerId");
			return (Criteria) this;
		}

		public Criteria andManagerIdNotLike(String value) {
			addCriterion("manager_id not like", value, "managerId");
			return (Criteria) this;
		}

		public Criteria andManagerIdIn(List<String> values) {
			addCriterion("manager_id in", values, "managerId");
			return (Criteria) this;
		}

		public Criteria andManagerIdNotIn(List<String> values) {
			addCriterion("manager_id not in", values, "managerId");
			return (Criteria) this;
		}

		public Criteria andManagerIdBetween(String value1, String value2) {
			addCriterion("manager_id between", value1, value2, "managerId");
			return (Criteria) this;
		}

		public Criteria andManagerIdNotBetween(String value1, String value2) {
			addCriterion("manager_id not between", value1, value2, "managerId");
			return (Criteria) this;
		}

		public Criteria andReservationDeleteFlgIsNull() {
			addCriterion("reservation_delete_flg is null");
			return (Criteria) this;
		}

		public Criteria andReservationDeleteFlgIsNotNull() {
			addCriterion("reservation_delete_flg is not null");
			return (Criteria) this;
		}

		public Criteria andReservationDeleteFlgEqualTo(Integer value) {
			addCriterion("reservation_delete_flg =", value, "reservationDeleteFlg");
			return (Criteria) this;
		}

		public Criteria andReservationDeleteFlgNotEqualTo(Integer value) {
			addCriterion("reservation_delete_flg <>", value, "reservationDeleteFlg");
			return (Criteria) this;
		}

		public Criteria andReservationDeleteFlgGreaterThan(Integer value) {
			addCriterion("reservation_delete_flg >", value, "reservationDeleteFlg");
			return (Criteria) this;
		}

		public Criteria andReservationDeleteFlgGreaterThanOrEqualTo(Integer value) {
			addCriterion("reservation_delete_flg >=", value, "reservationDeleteFlg");
			return (Criteria) this;
		}

		public Criteria andReservationDeleteFlgLessThan(Integer value) {
			addCriterion("reservation_delete_flg <", value, "reservationDeleteFlg");
			return (Criteria) this;
		}

		public Criteria andReservationDeleteFlgLessThanOrEqualTo(Integer value) {
			addCriterion("reservation_delete_flg <=", value, "reservationDeleteFlg");
			return (Criteria) this;
		}

		public Criteria andReservationDeleteFlgIn(List<Integer> values) {
			addCriterion("reservation_delete_flg in", values, "reservationDeleteFlg");
			return (Criteria) this;
		}

		public Criteria andReservationDeleteFlgNotIn(List<Integer> values) {
			addCriterion("reservation_delete_flg not in", values, "reservationDeleteFlg");
			return (Criteria) this;
		}

		public Criteria andReservationDeleteFlgBetween(Integer value1, Integer value2) {
			addCriterion("reservation_delete_flg between", value1, value2, "reservationDeleteFlg");
			return (Criteria) this;
		}

		public Criteria andReservationDeleteFlgNotBetween(Integer value1, Integer value2) {
			addCriterion("reservation_delete_flg not between", value1, value2, "reservationDeleteFlg");
			return (Criteria) this;
		}

		public Criteria andJudgmentFlgIsNull() {
			addCriterion("judgment_flg is null");
			return (Criteria) this;
		}

		public Criteria andJudgmentFlgIsNotNull() {
			addCriterion("judgment_flg is not null");
			return (Criteria) this;
		}

		public Criteria andJudgmentFlgEqualTo(Integer value) {
			addCriterion("judgment_flg =", value, "judgmentFlg");
			return (Criteria) this;
		}

		public Criteria andJudgmentFlgNotEqualTo(Integer value) {
			addCriterion("judgment_flg <>", value, "judgmentFlg");
			return (Criteria) this;
		}

		public Criteria andJudgmentFlgGreaterThan(Integer value) {
			addCriterion("judgment_flg >", value, "judgmentFlg");
			return (Criteria) this;
		}

		public Criteria andJudgmentFlgGreaterThanOrEqualTo(Integer value) {
			addCriterion("judgment_flg >=", value, "judgmentFlg");
			return (Criteria) this;
		}

		public Criteria andJudgmentFlgLessThan(Integer value) {
			addCriterion("judgment_flg <", value, "judgmentFlg");
			return (Criteria) this;
		}

		public Criteria andJudgmentFlgLessThanOrEqualTo(Integer value) {
			addCriterion("judgment_flg <=", value, "judgmentFlg");
			return (Criteria) this;
		}

		public Criteria andJudgmentFlgIn(List<Integer> values) {
			addCriterion("judgment_flg in", values, "judgmentFlg");
			return (Criteria) this;
		}

		public Criteria andJudgmentFlgNotIn(List<Integer> values) {
			addCriterion("judgment_flg not in", values, "judgmentFlg");
			return (Criteria) this;
		}

		public Criteria andJudgmentFlgBetween(Integer value1, Integer value2) {
			addCriterion("judgment_flg between", value1, value2, "judgmentFlg");
			return (Criteria) this;
		}

		public Criteria andJudgmentFlgNotBetween(Integer value1, Integer value2) {
			addCriterion("judgment_flg not between", value1, value2, "judgmentFlg");
			return (Criteria) this;
		}

		public Criteria andResarvationCreateDateIsNull() {
			addCriterion("resarvation_create_date is null");
			return (Criteria) this;
		}

		public Criteria andResarvationCreateDateIsNotNull() {
			addCriterion("resarvation_create_date is not null");
			return (Criteria) this;
		}

		public Criteria andResarvationCreateDateEqualTo(Date value) {
			addCriterion("resarvation_create_date =", value, "resarvationCreateDate");
			return (Criteria) this;
		}

		public Criteria andResarvationCreateDateNotEqualTo(Date value) {
			addCriterion("resarvation_create_date <>", value, "resarvationCreateDate");
			return (Criteria) this;
		}

		public Criteria andResarvationCreateDateGreaterThan(Date value) {
			addCriterion("resarvation_create_date >", value, "resarvationCreateDate");
			return (Criteria) this;
		}

		public Criteria andResarvationCreateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("resarvation_create_date >=", value, "resarvationCreateDate");
			return (Criteria) this;
		}

		public Criteria andResarvationCreateDateLessThan(Date value) {
			addCriterion("resarvation_create_date <", value, "resarvationCreateDate");
			return (Criteria) this;
		}

		public Criteria andResarvationCreateDateLessThanOrEqualTo(Date value) {
			addCriterion("resarvation_create_date <=", value, "resarvationCreateDate");
			return (Criteria) this;
		}

		public Criteria andResarvationCreateDateIn(List<Date> values) {
			addCriterion("resarvation_create_date in", values, "resarvationCreateDate");
			return (Criteria) this;
		}

		public Criteria andResarvationCreateDateNotIn(List<Date> values) {
			addCriterion("resarvation_create_date not in", values, "resarvationCreateDate");
			return (Criteria) this;
		}

		public Criteria andResarvationCreateDateBetween(Date value1, Date value2) {
			addCriterion("resarvation_create_date between", value1, value2, "resarvationCreateDate");
			return (Criteria) this;
		}

		public Criteria andResarvationCreateDateNotBetween(Date value1, Date value2) {
			addCriterion("resarvation_create_date not between", value1, value2, "resarvationCreateDate");
			return (Criteria) this;
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andOwnerPhoneNumberIsNull() {
			addCriterion("owner_phone_number is null");
			return (Criteria) this;
		}

		public Criteria andOwnerPhoneNumberIsNotNull() {
			addCriterion("owner_phone_number is not null");
			return (Criteria) this;
		}

		public Criteria andOwnerPhoneNumberEqualTo(String value) {
			addCriterion("owner_phone_number =", value, "ownerPhoneNumber");
			return (Criteria) this;
		}

		public Criteria andOwnerPhoneNumberNotEqualTo(String value) {
			addCriterion("owner_phone_number <>", value, "ownerPhoneNumber");
			return (Criteria) this;
		}

		public Criteria andOwnerPhoneNumberGreaterThan(String value) {
			addCriterion("owner_phone_number >", value, "ownerPhoneNumber");
			return (Criteria) this;
		}

		public Criteria andOwnerPhoneNumberGreaterThanOrEqualTo(String value) {
			addCriterion("owner_phone_number >=", value, "ownerPhoneNumber");
			return (Criteria) this;
		}

		public Criteria andOwnerPhoneNumberLessThan(String value) {
			addCriterion("owner_phone_number <", value, "ownerPhoneNumber");
			return (Criteria) this;
		}

		public Criteria andOwnerPhoneNumberLessThanOrEqualTo(String value) {
			addCriterion("owner_phone_number <=", value, "ownerPhoneNumber");
			return (Criteria) this;
		}

		public Criteria andOwnerPhoneNumberLike(String value) {
			addCriterion("owner_phone_number like", value, "ownerPhoneNumber");
			return (Criteria) this;
		}

		public Criteria andOwnerPhoneNumberNotLike(String value) {
			addCriterion("owner_phone_number not like", value, "ownerPhoneNumber");
			return (Criteria) this;
		}

		public Criteria andOwnerPhoneNumberIn(List<String> values) {
			addCriterion("owner_phone_number in", values, "ownerPhoneNumber");
			return (Criteria) this;
		}

		public Criteria andOwnerPhoneNumberNotIn(List<String> values) {
			addCriterion("owner_phone_number not in", values, "ownerPhoneNumber");
			return (Criteria) this;
		}

		public Criteria andOwnerPhoneNumberBetween(String value1, String value2) {
			addCriterion("owner_phone_number between", value1, value2, "ownerPhoneNumber");
			return (Criteria) this;
		}

		public Criteria andOwnerPhoneNumberNotBetween(String value1, String value2) {
			addCriterion("owner_phone_number not between", value1, value2, "ownerPhoneNumber");
			return (Criteria) this;
		}

		public Criteria andStampQrTextIsNull() {
			addCriterion("stamp_qr_text is null");
			return (Criteria) this;
		}

		public Criteria andStampQrTextIsNotNull() {
			addCriterion("stamp_qr_text is not null");
			return (Criteria) this;
		}

		public Criteria andStampQrTextEqualTo(String value) {
			addCriterion("stamp_qr_text =", value, "stampQrText");
			return (Criteria) this;
		}

		public Criteria andStampQrTextNotEqualTo(String value) {
			addCriterion("stamp_qr_text <>", value, "stampQrText");
			return (Criteria) this;
		}

		public Criteria andStampQrTextGreaterThan(String value) {
			addCriterion("stamp_qr_text >", value, "stampQrText");
			return (Criteria) this;
		}

		public Criteria andStampQrTextGreaterThanOrEqualTo(String value) {
			addCriterion("stamp_qr_text >=", value, "stampQrText");
			return (Criteria) this;
		}

		public Criteria andStampQrTextLessThan(String value) {
			addCriterion("stamp_qr_text <", value, "stampQrText");
			return (Criteria) this;
		}

		public Criteria andStampQrTextLessThanOrEqualTo(String value) {
			addCriterion("stamp_qr_text <=", value, "stampQrText");
			return (Criteria) this;
		}

		public Criteria andStampQrTextLike(String value) {
			addCriterion("stamp_qr_text like", value, "stampQrText");
			return (Criteria) this;
		}

		public Criteria andStampQrTextNotLike(String value) {
			addCriterion("stamp_qr_text not like", value, "stampQrText");
			return (Criteria) this;
		}

		public Criteria andStampQrTextIn(List<String> values) {
			addCriterion("stamp_qr_text in", values, "stampQrText");
			return (Criteria) this;
		}

		public Criteria andStampQrTextNotIn(List<String> values) {
			addCriterion("stamp_qr_text not in", values, "stampQrText");
			return (Criteria) this;
		}

		public Criteria andStampQrTextBetween(String value1, String value2) {
			addCriterion("stamp_qr_text between", value1, value2, "stampQrText");
			return (Criteria) this;
		}

		public Criteria andStampQrTextNotBetween(String value1, String value2) {
			addCriterion("stamp_qr_text not between", value1, value2, "stampQrText");
			return (Criteria) this;
		}

		public Criteria andStampNameIsNull() {
			addCriterion("stamp_name is null");
			return (Criteria) this;
		}

		public Criteria andStampNameIsNotNull() {
			addCriterion("stamp_name is not null");
			return (Criteria) this;
		}

		public Criteria andStampNameEqualTo(String value) {
			addCriterion("stamp_name =", value, "stampName");
			return (Criteria) this;
		}

		public Criteria andStampNameNotEqualTo(String value) {
			addCriterion("stamp_name <>", value, "stampName");
			return (Criteria) this;
		}

		public Criteria andStampNameGreaterThan(String value) {
			addCriterion("stamp_name >", value, "stampName");
			return (Criteria) this;
		}

		public Criteria andStampNameGreaterThanOrEqualTo(String value) {
			addCriterion("stamp_name >=", value, "stampName");
			return (Criteria) this;
		}

		public Criteria andStampNameLessThan(String value) {
			addCriterion("stamp_name <", value, "stampName");
			return (Criteria) this;
		}

		public Criteria andStampNameLessThanOrEqualTo(String value) {
			addCriterion("stamp_name <=", value, "stampName");
			return (Criteria) this;
		}

		public Criteria andStampNameLike(String value) {
			addCriterion("stamp_name like", value, "stampName");
			return (Criteria) this;
		}

		public Criteria andStampNameNotLike(String value) {
			addCriterion("stamp_name not like", value, "stampName");
			return (Criteria) this;
		}

		public Criteria andStampNameIn(List<String> values) {
			addCriterion("stamp_name in", values, "stampName");
			return (Criteria) this;
		}

		public Criteria andStampNameNotIn(List<String> values) {
			addCriterion("stamp_name not in", values, "stampName");
			return (Criteria) this;
		}

		public Criteria andStampNameBetween(String value1, String value2) {
			addCriterion("stamp_name between", value1, value2, "stampName");
			return (Criteria) this;
		}

		public Criteria andStampNameNotBetween(String value1, String value2) {
			addCriterion("stamp_name not between", value1, value2, "stampName");
			return (Criteria) this;
		}

		public Criteria andStampRowIsNull() {
			addCriterion("stamp_row is null");
			return (Criteria) this;
		}

		public Criteria andStampRowIsNotNull() {
			addCriterion("stamp_row is not null");
			return (Criteria) this;
		}

		public Criteria andStampRowEqualTo(Integer value) {
			addCriterion("stamp_row =", value, "stampRow");
			return (Criteria) this;
		}

		public Criteria andStampRowNotEqualTo(Integer value) {
			addCriterion("stamp_row <>", value, "stampRow");
			return (Criteria) this;
		}

		public Criteria andStampRowGreaterThan(Integer value) {
			addCriterion("stamp_row >", value, "stampRow");
			return (Criteria) this;
		}

		public Criteria andStampRowGreaterThanOrEqualTo(Integer value) {
			addCriterion("stamp_row >=", value, "stampRow");
			return (Criteria) this;
		}

		public Criteria andStampRowLessThan(Integer value) {
			addCriterion("stamp_row <", value, "stampRow");
			return (Criteria) this;
		}

		public Criteria andStampRowLessThanOrEqualTo(Integer value) {
			addCriterion("stamp_row <=", value, "stampRow");
			return (Criteria) this;
		}

		public Criteria andStampRowIn(List<Integer> values) {
			addCriterion("stamp_row in", values, "stampRow");
			return (Criteria) this;
		}

		public Criteria andStampRowNotIn(List<Integer> values) {
			addCriterion("stamp_row not in", values, "stampRow");
			return (Criteria) this;
		}

		public Criteria andStampRowBetween(Integer value1, Integer value2) {
			addCriterion("stamp_row between", value1, value2, "stampRow");
			return (Criteria) this;
		}

		public Criteria andStampRowNotBetween(Integer value1, Integer value2) {
			addCriterion("stamp_row not between", value1, value2, "stampRow");
			return (Criteria) this;
		}

		public Criteria andStampColIsNull() {
			addCriterion("stamp_col is null");
			return (Criteria) this;
		}

		public Criteria andStampColIsNotNull() {
			addCriterion("stamp_col is not null");
			return (Criteria) this;
		}

		public Criteria andStampColEqualTo(Integer value) {
			addCriterion("stamp_col =", value, "stampCol");
			return (Criteria) this;
		}

		public Criteria andStampColNotEqualTo(Integer value) {
			addCriterion("stamp_col <>", value, "stampCol");
			return (Criteria) this;
		}

		public Criteria andStampColGreaterThan(Integer value) {
			addCriterion("stamp_col >", value, "stampCol");
			return (Criteria) this;
		}

		public Criteria andStampColGreaterThanOrEqualTo(Integer value) {
			addCriterion("stamp_col >=", value, "stampCol");
			return (Criteria) this;
		}

		public Criteria andStampColLessThan(Integer value) {
			addCriterion("stamp_col <", value, "stampCol");
			return (Criteria) this;
		}

		public Criteria andStampColLessThanOrEqualTo(Integer value) {
			addCriterion("stamp_col <=", value, "stampCol");
			return (Criteria) this;
		}

		public Criteria andStampColIn(List<Integer> values) {
			addCriterion("stamp_col in", values, "stampCol");
			return (Criteria) this;
		}

		public Criteria andStampColNotIn(List<Integer> values) {
			addCriterion("stamp_col not in", values, "stampCol");
			return (Criteria) this;
		}

		public Criteria andStampColBetween(Integer value1, Integer value2) {
			addCriterion("stamp_col between", value1, value2, "stampCol");
			return (Criteria) this;
		}

		public Criteria andStampColNotBetween(Integer value1, Integer value2) {
			addCriterion("stamp_col not between", value1, value2, "stampCol");
			return (Criteria) this;
		}

		public Criteria andStampImgIsNull() {
			addCriterion("stamp_img is null");
			return (Criteria) this;
		}

		public Criteria andStampImgIsNotNull() {
			addCriterion("stamp_img is not null");
			return (Criteria) this;
		}

		public Criteria andStampImgEqualTo(String value) {
			addCriterion("stamp_img =", value, "stampImg");
			return (Criteria) this;
		}

		public Criteria andStampImgNotEqualTo(String value) {
			addCriterion("stamp_img <>", value, "stampImg");
			return (Criteria) this;
		}

		public Criteria andStampImgGreaterThan(String value) {
			addCriterion("stamp_img >", value, "stampImg");
			return (Criteria) this;
		}

		public Criteria andStampImgGreaterThanOrEqualTo(String value) {
			addCriterion("stamp_img >=", value, "stampImg");
			return (Criteria) this;
		}

		public Criteria andStampImgLessThan(String value) {
			addCriterion("stamp_img <", value, "stampImg");
			return (Criteria) this;
		}

		public Criteria andStampImgLessThanOrEqualTo(String value) {
			addCriterion("stamp_img <=", value, "stampImg");
			return (Criteria) this;
		}

		public Criteria andStampImgLike(String value) {
			addCriterion("stamp_img like", value, "stampImg");
			return (Criteria) this;
		}

		public Criteria andStampImgNotLike(String value) {
			addCriterion("stamp_img not like", value, "stampImg");
			return (Criteria) this;
		}

		public Criteria andStampImgIn(List<String> values) {
			addCriterion("stamp_img in", values, "stampImg");
			return (Criteria) this;
		}

		public Criteria andStampImgNotIn(List<String> values) {
			addCriterion("stamp_img not in", values, "stampImg");
			return (Criteria) this;
		}

		public Criteria andStampImgBetween(String value1, String value2) {
			addCriterion("stamp_img between", value1, value2, "stampImg");
			return (Criteria) this;
		}

		public Criteria andStampImgNotBetween(String value1, String value2) {
			addCriterion("stamp_img not between", value1, value2, "stampImg");
			return (Criteria) this;
		}

		public Criteria andStampBackImgIsNull() {
			addCriterion("stamp_back_img is null");
			return (Criteria) this;
		}

		public Criteria andStampBackImgIsNotNull() {
			addCriterion("stamp_back_img is not null");
			return (Criteria) this;
		}

		public Criteria andStampBackImgEqualTo(String value) {
			addCriterion("stamp_back_img =", value, "stampBackImg");
			return (Criteria) this;
		}

		public Criteria andStampBackImgNotEqualTo(String value) {
			addCriterion("stamp_back_img <>", value, "stampBackImg");
			return (Criteria) this;
		}

		public Criteria andStampBackImgGreaterThan(String value) {
			addCriterion("stamp_back_img >", value, "stampBackImg");
			return (Criteria) this;
		}

		public Criteria andStampBackImgGreaterThanOrEqualTo(String value) {
			addCriterion("stamp_back_img >=", value, "stampBackImg");
			return (Criteria) this;
		}

		public Criteria andStampBackImgLessThan(String value) {
			addCriterion("stamp_back_img <", value, "stampBackImg");
			return (Criteria) this;
		}

		public Criteria andStampBackImgLessThanOrEqualTo(String value) {
			addCriterion("stamp_back_img <=", value, "stampBackImg");
			return (Criteria) this;
		}

		public Criteria andStampBackImgLike(String value) {
			addCriterion("stamp_back_img like", value, "stampBackImg");
			return (Criteria) this;
		}

		public Criteria andStampBackImgNotLike(String value) {
			addCriterion("stamp_back_img not like", value, "stampBackImg");
			return (Criteria) this;
		}

		public Criteria andStampBackImgIn(List<String> values) {
			addCriterion("stamp_back_img in", values, "stampBackImg");
			return (Criteria) this;
		}

		public Criteria andStampBackImgNotIn(List<String> values) {
			addCriterion("stamp_back_img not in", values, "stampBackImg");
			return (Criteria) this;
		}

		public Criteria andStampBackImgBetween(String value1, String value2) {
			addCriterion("stamp_back_img between", value1, value2, "stampBackImg");
			return (Criteria) this;
		}

		public Criteria andStampBackImgNotBetween(String value1, String value2) {
			addCriterion("stamp_back_img not between", value1, value2, "stampBackImg");
			return (Criteria) this;
		}

		public Criteria andValidityStartDateIsNull() {
			addCriterion("validity_start_date is null");
			return (Criteria) this;
		}

		public Criteria andValidityStartDateIsNotNull() {
			addCriterion("validity_start_date is not null");
			return (Criteria) this;
		}

		public Criteria andValidityStartDateEqualTo(Date value) {
			addCriterion("validity_start_date =", value, "validityStartDate");
			return (Criteria) this;
		}

		public Criteria andValidityStartDateNotEqualTo(Date value) {
			addCriterion("validity_start_date <>", value, "validityStartDate");
			return (Criteria) this;
		}

		public Criteria andValidityStartDateGreaterThan(Date value) {
			addCriterion("validity_start_date >", value, "validityStartDate");
			return (Criteria) this;
		}

		public Criteria andValidityStartDateGreaterThanOrEqualTo(Date value) {
			addCriterion("validity_start_date >=", value, "validityStartDate");
			return (Criteria) this;
		}

		public Criteria andValidityStartDateLessThan(Date value) {
			addCriterion("validity_start_date <", value, "validityStartDate");
			return (Criteria) this;
		}

		public Criteria andValidityStartDateLessThanOrEqualTo(Date value) {
			addCriterion("validity_start_date <=", value, "validityStartDate");
			return (Criteria) this;
		}

		public Criteria andValidityStartDateIn(List<Date> values) {
			addCriterion("validity_start_date in", values, "validityStartDate");
			return (Criteria) this;
		}

		public Criteria andValidityStartDateNotIn(List<Date> values) {
			addCriterion("validity_start_date not in", values, "validityStartDate");
			return (Criteria) this;
		}

		public Criteria andValidityStartDateBetween(Date value1, Date value2) {
			addCriterion("validity_start_date between", value1, value2, "validityStartDate");
			return (Criteria) this;
		}

		public Criteria andValidityStartDateNotBetween(Date value1, Date value2) {
			addCriterion("validity_start_date not between", value1, value2, "validityStartDate");
			return (Criteria) this;
		}

		public Criteria andValidityEndDateIsNull() {
			addCriterion("validity_end_date is null");
			return (Criteria) this;
		}

		public Criteria andValidityEndDateIsNotNull() {
			addCriterion("validity_end_date is not null");
			return (Criteria) this;
		}

		public Criteria andValidityEndDateEqualTo(Date value) {
			addCriterion("validity_end_date =", value, "validityEndDate");
			return (Criteria) this;
		}

		public Criteria andValidityEndDateNotEqualTo(Date value) {
			addCriterion("validity_end_date <>", value, "validityEndDate");
			return (Criteria) this;
		}

		public Criteria andValidityEndDateGreaterThan(Date value) {
			addCriterion("validity_end_date >", value, "validityEndDate");
			return (Criteria) this;
		}

		public Criteria andValidityEndDateGreaterThanOrEqualTo(Date value) {
			addCriterion("validity_end_date >=", value, "validityEndDate");
			return (Criteria) this;
		}

		public Criteria andValidityEndDateLessThan(Date value) {
			addCriterion("validity_end_date <", value, "validityEndDate");
			return (Criteria) this;
		}

		public Criteria andValidityEndDateLessThanOrEqualTo(Date value) {
			addCriterion("validity_end_date <=", value, "validityEndDate");
			return (Criteria) this;
		}

		public Criteria andValidityEndDateIn(List<Date> values) {
			addCriterion("validity_end_date in", values, "validityEndDate");
			return (Criteria) this;
		}

		public Criteria andValidityEndDateNotIn(List<Date> values) {
			addCriterion("validity_end_date not in", values, "validityEndDate");
			return (Criteria) this;
		}

		public Criteria andValidityEndDateBetween(Date value1, Date value2) {
			addCriterion("validity_end_date between", value1, value2, "validityEndDate");
			return (Criteria) this;
		}

		public Criteria andValidityEndDateNotBetween(Date value1, Date value2) {
			addCriterion("validity_end_date not between", value1, value2, "validityEndDate");
			return (Criteria) this;
		}

		public Criteria andValidityPlusDateIsNull() {
			addCriterion("validity_plus_date is null");
			return (Criteria) this;
		}

		public Criteria andValidityPlusDateIsNotNull() {
			addCriterion("validity_plus_date is not null");
			return (Criteria) this;
		}

		public Criteria andValidityPlusDateEqualTo(Integer value) {
			addCriterion("validity_plus_date =", value, "validityPlusDate");
			return (Criteria) this;
		}

		public Criteria andValidityPlusDateNotEqualTo(Integer value) {
			addCriterion("validity_plus_date <>", value, "validityPlusDate");
			return (Criteria) this;
		}

		public Criteria andValidityPlusDateGreaterThan(Integer value) {
			addCriterion("validity_plus_date >", value, "validityPlusDate");
			return (Criteria) this;
		}

		public Criteria andValidityPlusDateGreaterThanOrEqualTo(Integer value) {
			addCriterion("validity_plus_date >=", value, "validityPlusDate");
			return (Criteria) this;
		}

		public Criteria andValidityPlusDateLessThan(Integer value) {
			addCriterion("validity_plus_date <", value, "validityPlusDate");
			return (Criteria) this;
		}

		public Criteria andValidityPlusDateLessThanOrEqualTo(Integer value) {
			addCriterion("validity_plus_date <=", value, "validityPlusDate");
			return (Criteria) this;
		}

		public Criteria andValidityPlusDateIn(List<Integer> values) {
			addCriterion("validity_plus_date in", values, "validityPlusDate");
			return (Criteria) this;
		}

		public Criteria andValidityPlusDateNotIn(List<Integer> values) {
			addCriterion("validity_plus_date not in", values, "validityPlusDate");
			return (Criteria) this;
		}

		public Criteria andValidityPlusDateBetween(Integer value1, Integer value2) {
			addCriterion("validity_plus_date between", value1, value2, "validityPlusDate");
			return (Criteria) this;
		}

		public Criteria andValidityPlusDateNotBetween(Integer value1, Integer value2) {
			addCriterion("validity_plus_date not between", value1, value2, "validityPlusDate");
			return (Criteria) this;
		}

		public Criteria andValidityPlusTypeIsNull() {
			addCriterion("validity_plus_type is null");
			return (Criteria) this;
		}

		public Criteria andValidityPlusTypeIsNotNull() {
			addCriterion("validity_plus_type is not null");
			return (Criteria) this;
		}

		public Criteria andValidityPlusTypeEqualTo(Integer value) {
			addCriterion("validity_plus_type =", value, "validityPlusType");
			return (Criteria) this;
		}

		public Criteria andValidityPlusTypeNotEqualTo(Integer value) {
			addCriterion("validity_plus_type <>", value, "validityPlusType");
			return (Criteria) this;
		}

		public Criteria andValidityPlusTypeGreaterThan(Integer value) {
			addCriterion("validity_plus_type >", value, "validityPlusType");
			return (Criteria) this;
		}

		public Criteria andValidityPlusTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("validity_plus_type >=", value, "validityPlusType");
			return (Criteria) this;
		}

		public Criteria andValidityPlusTypeLessThan(Integer value) {
			addCriterion("validity_plus_type <", value, "validityPlusType");
			return (Criteria) this;
		}

		public Criteria andValidityPlusTypeLessThanOrEqualTo(Integer value) {
			addCriterion("validity_plus_type <=", value, "validityPlusType");
			return (Criteria) this;
		}

		public Criteria andValidityPlusTypeIn(List<Integer> values) {
			addCriterion("validity_plus_type in", values, "validityPlusType");
			return (Criteria) this;
		}

		public Criteria andValidityPlusTypeNotIn(List<Integer> values) {
			addCriterion("validity_plus_type not in", values, "validityPlusType");
			return (Criteria) this;
		}

		public Criteria andValidityPlusTypeBetween(Integer value1, Integer value2) {
			addCriterion("validity_plus_type between", value1, value2, "validityPlusType");
			return (Criteria) this;
		}

		public Criteria andValidityPlusTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("validity_plus_type not between", value1, value2, "validityPlusType");
			return (Criteria) this;
		}

		public Criteria andValidityTypeIsNull() {
			addCriterion("validity_type is null");
			return (Criteria) this;
		}

		public Criteria andValidityTypeIsNotNull() {
			addCriterion("validity_type is not null");
			return (Criteria) this;
		}

		public Criteria andValidityTypeEqualTo(Integer value) {
			addCriterion("validity_type =", value, "validityType");
			return (Criteria) this;
		}

		public Criteria andValidityTypeNotEqualTo(Integer value) {
			addCriterion("validity_type <>", value, "validityType");
			return (Criteria) this;
		}

		public Criteria andValidityTypeGreaterThan(Integer value) {
			addCriterion("validity_type >", value, "validityType");
			return (Criteria) this;
		}

		public Criteria andValidityTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("validity_type >=", value, "validityType");
			return (Criteria) this;
		}

		public Criteria andValidityTypeLessThan(Integer value) {
			addCriterion("validity_type <", value, "validityType");
			return (Criteria) this;
		}

		public Criteria andValidityTypeLessThanOrEqualTo(Integer value) {
			addCriterion("validity_type <=", value, "validityType");
			return (Criteria) this;
		}

		public Criteria andValidityTypeIn(List<Integer> values) {
			addCriterion("validity_type in", values, "validityType");
			return (Criteria) this;
		}

		public Criteria andValidityTypeNotIn(List<Integer> values) {
			addCriterion("validity_type not in", values, "validityType");
			return (Criteria) this;
		}

		public Criteria andValidityTypeBetween(Integer value1, Integer value2) {
			addCriterion("validity_type between", value1, value2, "validityType");
			return (Criteria) this;
		}

		public Criteria andValidityTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("validity_type not between", value1, value2, "validityType");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgIsNull() {
			addCriterion("delete_flg is null");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgIsNotNull() {
			addCriterion("delete_flg is not null");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgEqualTo(Boolean value) {
			addCriterion("delete_flg =", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgNotEqualTo(Boolean value) {
			addCriterion("delete_flg <>", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgGreaterThan(Boolean value) {
			addCriterion("delete_flg >", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgGreaterThanOrEqualTo(Boolean value) {
			addCriterion("delete_flg >=", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgLessThan(Boolean value) {
			addCriterion("delete_flg <", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgLessThanOrEqualTo(Boolean value) {
			addCriterion("delete_flg <=", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgIn(List<Boolean> values) {
			addCriterion("delete_flg in", values, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgNotIn(List<Boolean> values) {
			addCriterion("delete_flg not in", values, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgBetween(Boolean value1, Boolean value2) {
			addCriterion("delete_flg between", value1, value2, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgNotBetween(Boolean value1, Boolean value2) {
			addCriterion("delete_flg not between", value1, value2, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNull() {
			addCriterion("create_date is null");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNotNull() {
			addCriterion("create_date is not null");
			return (Criteria) this;
		}

		public Criteria andCreateDateEqualTo(Date value) {
			addCriterion("create_date =", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotEqualTo(Date value) {
			addCriterion("create_date <>", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThan(Date value) {
			addCriterion("create_date >", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("create_date >=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThan(Date value) {
			addCriterion("create_date <", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThanOrEqualTo(Date value) {
			addCriterion("create_date <=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateIn(List<Date> values) {
			addCriterion("create_date in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotIn(List<Date> values) {
			addCriterion("create_date not in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateBetween(Date value1, Date value2) {
			addCriterion("create_date between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotBetween(Date value1, Date value2) {
			addCriterion("create_date not between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andStampThemeIsNull() {
			addCriterion("stamp_theme is null");
			return (Criteria) this;
		}

		public Criteria andStampThemeIsNotNull() {
			addCriterion("stamp_theme is not null");
			return (Criteria) this;
		}

		public Criteria andStampThemeEqualTo(Integer value) {
			addCriterion("stamp_theme =", value, "stampTheme");
			return (Criteria) this;
		}

		public Criteria andStampThemeNotEqualTo(Integer value) {
			addCriterion("stamp_theme <>", value, "stampTheme");
			return (Criteria) this;
		}

		public Criteria andStampThemeGreaterThan(Integer value) {
			addCriterion("stamp_theme >", value, "stampTheme");
			return (Criteria) this;
		}

		public Criteria andStampThemeGreaterThanOrEqualTo(Integer value) {
			addCriterion("stamp_theme >=", value, "stampTheme");
			return (Criteria) this;
		}

		public Criteria andStampThemeLessThan(Integer value) {
			addCriterion("stamp_theme <", value, "stampTheme");
			return (Criteria) this;
		}

		public Criteria andStampThemeLessThanOrEqualTo(Integer value) {
			addCriterion("stamp_theme <=", value, "stampTheme");
			return (Criteria) this;
		}

		public Criteria andStampThemeIn(List<Integer> values) {
			addCriterion("stamp_theme in", values, "stampTheme");
			return (Criteria) this;
		}

		public Criteria andStampThemeNotIn(List<Integer> values) {
			addCriterion("stamp_theme not in", values, "stampTheme");
			return (Criteria) this;
		}

		public Criteria andStampThemeBetween(Integer value1, Integer value2) {
			addCriterion("stamp_theme between", value1, value2, "stampTheme");
			return (Criteria) this;
		}

		public Criteria andStampThemeNotBetween(Integer value1, Integer value2) {
			addCriterion("stamp_theme not between", value1, value2, "stampTheme");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table reservation_stamp
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table reservation_stamp
     *
     * @mbg.generated do_not_delete_during_merge Mon Nov 16 16:02:40 KST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}