package com.dreamhanks.HappyBeautyManager.dto;

import java.util.Date;

public class ReservationOwner {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_owner.reservation_owner_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer reservationOwnerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_owner.manager_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String managerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_owner.reservation_delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer reservationDeleteFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_owner.judgment_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer judgmentFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_owner.resarvation_create_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Date resarvationCreateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_owner.owner_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer ownerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_owner.security_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String securityId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_owner.shop_name
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String shopName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_owner.shop_city
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer shopCity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_owner.shop_town
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer shopTown;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_owner.shop_phone_number
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String shopPhoneNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_owner.owner_phone_number
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String ownerPhoneNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_owner.owner_password
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String ownerPassword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_owner.auth
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String auth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_owner.delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Boolean deleteFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_owner.shop_img
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String shopImg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_owner.owner_login_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String ownerLoginId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_owner.shop_detail_address
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String shopDetailAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_owner.shop_type_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer shopTypeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_owner.shop_open_time
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String shopOpenTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_owner.shop_close_time
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String shopCloseTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_owner.reservation_interval_time
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String reservationIntervalTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_owner.create_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Date createDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_owner.reservation_owner_id
	 * @return  the value of reservation_owner.reservation_owner_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getReservationOwnerId() {
		return reservationOwnerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_owner.reservation_owner_id
	 * @param reservationOwnerId  the value for reservation_owner.reservation_owner_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setReservationOwnerId(Integer reservationOwnerId) {
		this.reservationOwnerId = reservationOwnerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_owner.manager_id
	 * @return  the value of reservation_owner.manager_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getManagerId() {
		return managerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_owner.manager_id
	 * @param managerId  the value for reservation_owner.manager_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setManagerId(String managerId) {
		this.managerId = managerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_owner.reservation_delete_flg
	 * @return  the value of reservation_owner.reservation_delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getReservationDeleteFlg() {
		return reservationDeleteFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_owner.reservation_delete_flg
	 * @param reservationDeleteFlg  the value for reservation_owner.reservation_delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setReservationDeleteFlg(Integer reservationDeleteFlg) {
		this.reservationDeleteFlg = reservationDeleteFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_owner.judgment_flg
	 * @return  the value of reservation_owner.judgment_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getJudgmentFlg() {
		return judgmentFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_owner.judgment_flg
	 * @param judgmentFlg  the value for reservation_owner.judgment_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setJudgmentFlg(Integer judgmentFlg) {
		this.judgmentFlg = judgmentFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_owner.resarvation_create_date
	 * @return  the value of reservation_owner.resarvation_create_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Date getResarvationCreateDate() {
		return resarvationCreateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_owner.resarvation_create_date
	 * @param resarvationCreateDate  the value for reservation_owner.resarvation_create_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setResarvationCreateDate(Date resarvationCreateDate) {
		this.resarvationCreateDate = resarvationCreateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_owner.owner_id
	 * @return  the value of reservation_owner.owner_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getOwnerId() {
		return ownerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_owner.owner_id
	 * @param ownerId  the value for reservation_owner.owner_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setOwnerId(Integer ownerId) {
		this.ownerId = ownerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_owner.security_id
	 * @return  the value of reservation_owner.security_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getSecurityId() {
		return securityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_owner.security_id
	 * @param securityId  the value for reservation_owner.security_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setSecurityId(String securityId) {
		this.securityId = securityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_owner.shop_name
	 * @return  the value of reservation_owner.shop_name
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getShopName() {
		return shopName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_owner.shop_name
	 * @param shopName  the value for reservation_owner.shop_name
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setShopName(String shopName) {
		this.shopName = shopName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_owner.shop_city
	 * @return  the value of reservation_owner.shop_city
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getShopCity() {
		return shopCity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_owner.shop_city
	 * @param shopCity  the value for reservation_owner.shop_city
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setShopCity(Integer shopCity) {
		this.shopCity = shopCity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_owner.shop_town
	 * @return  the value of reservation_owner.shop_town
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getShopTown() {
		return shopTown;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_owner.shop_town
	 * @param shopTown  the value for reservation_owner.shop_town
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setShopTown(Integer shopTown) {
		this.shopTown = shopTown;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_owner.shop_phone_number
	 * @return  the value of reservation_owner.shop_phone_number
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getShopPhoneNumber() {
		return shopPhoneNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_owner.shop_phone_number
	 * @param shopPhoneNumber  the value for reservation_owner.shop_phone_number
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setShopPhoneNumber(String shopPhoneNumber) {
		this.shopPhoneNumber = shopPhoneNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_owner.owner_phone_number
	 * @return  the value of reservation_owner.owner_phone_number
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getOwnerPhoneNumber() {
		return ownerPhoneNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_owner.owner_phone_number
	 * @param ownerPhoneNumber  the value for reservation_owner.owner_phone_number
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setOwnerPhoneNumber(String ownerPhoneNumber) {
		this.ownerPhoneNumber = ownerPhoneNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_owner.owner_password
	 * @return  the value of reservation_owner.owner_password
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getOwnerPassword() {
		return ownerPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_owner.owner_password
	 * @param ownerPassword  the value for reservation_owner.owner_password
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setOwnerPassword(String ownerPassword) {
		this.ownerPassword = ownerPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_owner.auth
	 * @return  the value of reservation_owner.auth
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getAuth() {
		return auth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_owner.auth
	 * @param auth  the value for reservation_owner.auth
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setAuth(String auth) {
		this.auth = auth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_owner.delete_flg
	 * @return  the value of reservation_owner.delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Boolean getDeleteFlg() {
		return deleteFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_owner.delete_flg
	 * @param deleteFlg  the value for reservation_owner.delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setDeleteFlg(Boolean deleteFlg) {
		this.deleteFlg = deleteFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_owner.shop_img
	 * @return  the value of reservation_owner.shop_img
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getShopImg() {
		return shopImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_owner.shop_img
	 * @param shopImg  the value for reservation_owner.shop_img
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setShopImg(String shopImg) {
		this.shopImg = shopImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_owner.owner_login_id
	 * @return  the value of reservation_owner.owner_login_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getOwnerLoginId() {
		return ownerLoginId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_owner.owner_login_id
	 * @param ownerLoginId  the value for reservation_owner.owner_login_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setOwnerLoginId(String ownerLoginId) {
		this.ownerLoginId = ownerLoginId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_owner.shop_detail_address
	 * @return  the value of reservation_owner.shop_detail_address
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getShopDetailAddress() {
		return shopDetailAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_owner.shop_detail_address
	 * @param shopDetailAddress  the value for reservation_owner.shop_detail_address
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setShopDetailAddress(String shopDetailAddress) {
		this.shopDetailAddress = shopDetailAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_owner.shop_type_id
	 * @return  the value of reservation_owner.shop_type_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getShopTypeId() {
		return shopTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_owner.shop_type_id
	 * @param shopTypeId  the value for reservation_owner.shop_type_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setShopTypeId(Integer shopTypeId) {
		this.shopTypeId = shopTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_owner.shop_open_time
	 * @return  the value of reservation_owner.shop_open_time
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getShopOpenTime() {
		return shopOpenTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_owner.shop_open_time
	 * @param shopOpenTime  the value for reservation_owner.shop_open_time
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setShopOpenTime(String shopOpenTime) {
		this.shopOpenTime = shopOpenTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_owner.shop_close_time
	 * @return  the value of reservation_owner.shop_close_time
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getShopCloseTime() {
		return shopCloseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_owner.shop_close_time
	 * @param shopCloseTime  the value for reservation_owner.shop_close_time
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setShopCloseTime(String shopCloseTime) {
		this.shopCloseTime = shopCloseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_owner.reservation_interval_time
	 * @return  the value of reservation_owner.reservation_interval_time
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getReservationIntervalTime() {
		return reservationIntervalTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_owner.reservation_interval_time
	 * @param reservationIntervalTime  the value for reservation_owner.reservation_interval_time
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setReservationIntervalTime(String reservationIntervalTime) {
		this.reservationIntervalTime = reservationIntervalTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_owner.create_date
	 * @return  the value of reservation_owner.create_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_owner.create_date
	 * @param createDate  the value for reservation_owner.create_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
}