package com.dreamhanks.HappyBeautyManager.dto;

import java.util.Date;

public class ReservationChargehistory {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_chargehistory.reservation_chargehistory_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer reservationChargehistoryId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_chargehistory.manager_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String managerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_chargehistory.reservation_delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer reservationDeleteFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_chargehistory.judgment_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer judgmentFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_chargehistory.resarvation_create_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Date resarvationCreateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_chargehistory.charge_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer chargeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_chargehistory.charge_money
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer chargeMoney;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_chargehistory.customer_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer customerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_chargehistory.owner_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer ownerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_chargehistory.charge_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Date chargeDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_chargehistory.delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Boolean deleteFlg;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_chargehistory.reservation_chargehistory_id
	 * @return  the value of reservation_chargehistory.reservation_chargehistory_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getReservationChargehistoryId() {
		return reservationChargehistoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_chargehistory.reservation_chargehistory_id
	 * @param reservationChargehistoryId  the value for reservation_chargehistory.reservation_chargehistory_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setReservationChargehistoryId(Integer reservationChargehistoryId) {
		this.reservationChargehistoryId = reservationChargehistoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_chargehistory.manager_id
	 * @return  the value of reservation_chargehistory.manager_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getManagerId() {
		return managerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_chargehistory.manager_id
	 * @param managerId  the value for reservation_chargehistory.manager_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setManagerId(String managerId) {
		this.managerId = managerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_chargehistory.reservation_delete_flg
	 * @return  the value of reservation_chargehistory.reservation_delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getReservationDeleteFlg() {
		return reservationDeleteFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_chargehistory.reservation_delete_flg
	 * @param reservationDeleteFlg  the value for reservation_chargehistory.reservation_delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setReservationDeleteFlg(Integer reservationDeleteFlg) {
		this.reservationDeleteFlg = reservationDeleteFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_chargehistory.judgment_flg
	 * @return  the value of reservation_chargehistory.judgment_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getJudgmentFlg() {
		return judgmentFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_chargehistory.judgment_flg
	 * @param judgmentFlg  the value for reservation_chargehistory.judgment_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setJudgmentFlg(Integer judgmentFlg) {
		this.judgmentFlg = judgmentFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_chargehistory.resarvation_create_date
	 * @return  the value of reservation_chargehistory.resarvation_create_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Date getResarvationCreateDate() {
		return resarvationCreateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_chargehistory.resarvation_create_date
	 * @param resarvationCreateDate  the value for reservation_chargehistory.resarvation_create_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setResarvationCreateDate(Date resarvationCreateDate) {
		this.resarvationCreateDate = resarvationCreateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_chargehistory.charge_id
	 * @return  the value of reservation_chargehistory.charge_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getChargeId() {
		return chargeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_chargehistory.charge_id
	 * @param chargeId  the value for reservation_chargehistory.charge_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setChargeId(Integer chargeId) {
		this.chargeId = chargeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_chargehistory.charge_money
	 * @return  the value of reservation_chargehistory.charge_money
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getChargeMoney() {
		return chargeMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_chargehistory.charge_money
	 * @param chargeMoney  the value for reservation_chargehistory.charge_money
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setChargeMoney(Integer chargeMoney) {
		this.chargeMoney = chargeMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_chargehistory.customer_id
	 * @return  the value of reservation_chargehistory.customer_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getCustomerId() {
		return customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_chargehistory.customer_id
	 * @param customerId  the value for reservation_chargehistory.customer_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_chargehistory.owner_id
	 * @return  the value of reservation_chargehistory.owner_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getOwnerId() {
		return ownerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_chargehistory.owner_id
	 * @param ownerId  the value for reservation_chargehistory.owner_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setOwnerId(Integer ownerId) {
		this.ownerId = ownerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_chargehistory.charge_date
	 * @return  the value of reservation_chargehistory.charge_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Date getChargeDate() {
		return chargeDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_chargehistory.charge_date
	 * @param chargeDate  the value for reservation_chargehistory.charge_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setChargeDate(Date chargeDate) {
		this.chargeDate = chargeDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_chargehistory.delete_flg
	 * @return  the value of reservation_chargehistory.delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Boolean getDeleteFlg() {
		return deleteFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_chargehistory.delete_flg
	 * @param deleteFlg  the value for reservation_chargehistory.delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setDeleteFlg(Boolean deleteFlg) {
		this.deleteFlg = deleteFlg;
	}
}