package com.dreamhanks.HappyBeautyManager.dto;

import java.util.ArrayList;
import java.util.List;

public class ReservationhistoryExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table reservationhistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table reservationhistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table reservationhistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservationhistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public ReservationhistoryExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservationhistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservationhistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservationhistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservationhistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservationhistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservationhistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservationhistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservationhistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservationhistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservationhistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table reservationhistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andReservationIdIsNull() {
			addCriterion("reservation_id is null");
			return (Criteria) this;
		}

		public Criteria andReservationIdIsNotNull() {
			addCriterion("reservation_id is not null");
			return (Criteria) this;
		}

		public Criteria andReservationIdEqualTo(Integer value) {
			addCriterion("reservation_id =", value, "reservationId");
			return (Criteria) this;
		}

		public Criteria andReservationIdNotEqualTo(Integer value) {
			addCriterion("reservation_id <>", value, "reservationId");
			return (Criteria) this;
		}

		public Criteria andReservationIdGreaterThan(Integer value) {
			addCriterion("reservation_id >", value, "reservationId");
			return (Criteria) this;
		}

		public Criteria andReservationIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("reservation_id >=", value, "reservationId");
			return (Criteria) this;
		}

		public Criteria andReservationIdLessThan(Integer value) {
			addCriterion("reservation_id <", value, "reservationId");
			return (Criteria) this;
		}

		public Criteria andReservationIdLessThanOrEqualTo(Integer value) {
			addCriterion("reservation_id <=", value, "reservationId");
			return (Criteria) this;
		}

		public Criteria andReservationIdIn(List<Integer> values) {
			addCriterion("reservation_id in", values, "reservationId");
			return (Criteria) this;
		}

		public Criteria andReservationIdNotIn(List<Integer> values) {
			addCriterion("reservation_id not in", values, "reservationId");
			return (Criteria) this;
		}

		public Criteria andReservationIdBetween(Integer value1, Integer value2) {
			addCriterion("reservation_id between", value1, value2, "reservationId");
			return (Criteria) this;
		}

		public Criteria andReservationIdNotBetween(Integer value1, Integer value2) {
			addCriterion("reservation_id not between", value1, value2, "reservationId");
			return (Criteria) this;
		}

		public Criteria andCustomerIdIsNull() {
			addCriterion("customer_id is null");
			return (Criteria) this;
		}

		public Criteria andCustomerIdIsNotNull() {
			addCriterion("customer_id is not null");
			return (Criteria) this;
		}

		public Criteria andCustomerIdEqualTo(Integer value) {
			addCriterion("customer_id =", value, "customerId");
			return (Criteria) this;
		}

		public Criteria andCustomerIdNotEqualTo(Integer value) {
			addCriterion("customer_id <>", value, "customerId");
			return (Criteria) this;
		}

		public Criteria andCustomerIdGreaterThan(Integer value) {
			addCriterion("customer_id >", value, "customerId");
			return (Criteria) this;
		}

		public Criteria andCustomerIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("customer_id >=", value, "customerId");
			return (Criteria) this;
		}

		public Criteria andCustomerIdLessThan(Integer value) {
			addCriterion("customer_id <", value, "customerId");
			return (Criteria) this;
		}

		public Criteria andCustomerIdLessThanOrEqualTo(Integer value) {
			addCriterion("customer_id <=", value, "customerId");
			return (Criteria) this;
		}

		public Criteria andCustomerIdIn(List<Integer> values) {
			addCriterion("customer_id in", values, "customerId");
			return (Criteria) this;
		}

		public Criteria andCustomerIdNotIn(List<Integer> values) {
			addCriterion("customer_id not in", values, "customerId");
			return (Criteria) this;
		}

		public Criteria andCustomerIdBetween(Integer value1, Integer value2) {
			addCriterion("customer_id between", value1, value2, "customerId");
			return (Criteria) this;
		}

		public Criteria andCustomerIdNotBetween(Integer value1, Integer value2) {
			addCriterion("customer_id not between", value1, value2, "customerId");
			return (Criteria) this;
		}

		public Criteria andOwnerIdIsNull() {
			addCriterion("owner_id is null");
			return (Criteria) this;
		}

		public Criteria andOwnerIdIsNotNull() {
			addCriterion("owner_id is not null");
			return (Criteria) this;
		}

		public Criteria andOwnerIdEqualTo(Integer value) {
			addCriterion("owner_id =", value, "ownerId");
			return (Criteria) this;
		}

		public Criteria andOwnerIdNotEqualTo(Integer value) {
			addCriterion("owner_id <>", value, "ownerId");
			return (Criteria) this;
		}

		public Criteria andOwnerIdGreaterThan(Integer value) {
			addCriterion("owner_id >", value, "ownerId");
			return (Criteria) this;
		}

		public Criteria andOwnerIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("owner_id >=", value, "ownerId");
			return (Criteria) this;
		}

		public Criteria andOwnerIdLessThan(Integer value) {
			addCriterion("owner_id <", value, "ownerId");
			return (Criteria) this;
		}

		public Criteria andOwnerIdLessThanOrEqualTo(Integer value) {
			addCriterion("owner_id <=", value, "ownerId");
			return (Criteria) this;
		}

		public Criteria andOwnerIdIn(List<Integer> values) {
			addCriterion("owner_id in", values, "ownerId");
			return (Criteria) this;
		}

		public Criteria andOwnerIdNotIn(List<Integer> values) {
			addCriterion("owner_id not in", values, "ownerId");
			return (Criteria) this;
		}

		public Criteria andOwnerIdBetween(Integer value1, Integer value2) {
			addCriterion("owner_id between", value1, value2, "ownerId");
			return (Criteria) this;
		}

		public Criteria andOwnerIdNotBetween(Integer value1, Integer value2) {
			addCriterion("owner_id not between", value1, value2, "ownerId");
			return (Criteria) this;
		}

		public Criteria andReservationDateIsNull() {
			addCriterion("reservation_date is null");
			return (Criteria) this;
		}

		public Criteria andReservationDateIsNotNull() {
			addCriterion("reservation_date is not null");
			return (Criteria) this;
		}

		public Criteria andReservationDateEqualTo(String value) {
			addCriterion("reservation_date =", value, "reservationDate");
			return (Criteria) this;
		}

		public Criteria andReservationDateNotEqualTo(String value) {
			addCriterion("reservation_date <>", value, "reservationDate");
			return (Criteria) this;
		}

		public Criteria andReservationDateGreaterThan(String value) {
			addCriterion("reservation_date >", value, "reservationDate");
			return (Criteria) this;
		}

		public Criteria andReservationDateGreaterThanOrEqualTo(String value) {
			addCriterion("reservation_date >=", value, "reservationDate");
			return (Criteria) this;
		}

		public Criteria andReservationDateLessThan(String value) {
			addCriterion("reservation_date <", value, "reservationDate");
			return (Criteria) this;
		}

		public Criteria andReservationDateLessThanOrEqualTo(String value) {
			addCriterion("reservation_date <=", value, "reservationDate");
			return (Criteria) this;
		}

		public Criteria andReservationDateLike(String value) {
			addCriterion("reservation_date like", value, "reservationDate");
			return (Criteria) this;
		}

		public Criteria andReservationDateNotLike(String value) {
			addCriterion("reservation_date not like", value, "reservationDate");
			return (Criteria) this;
		}

		public Criteria andReservationDateIn(List<String> values) {
			addCriterion("reservation_date in", values, "reservationDate");
			return (Criteria) this;
		}

		public Criteria andReservationDateNotIn(List<String> values) {
			addCriterion("reservation_date not in", values, "reservationDate");
			return (Criteria) this;
		}

		public Criteria andReservationDateBetween(String value1, String value2) {
			addCriterion("reservation_date between", value1, value2, "reservationDate");
			return (Criteria) this;
		}

		public Criteria andReservationDateNotBetween(String value1, String value2) {
			addCriterion("reservation_date not between", value1, value2, "reservationDate");
			return (Criteria) this;
		}

		public Criteria andReservationTimeIsNull() {
			addCriterion("reservation_time is null");
			return (Criteria) this;
		}

		public Criteria andReservationTimeIsNotNull() {
			addCriterion("reservation_time is not null");
			return (Criteria) this;
		}

		public Criteria andReservationTimeEqualTo(String value) {
			addCriterion("reservation_time =", value, "reservationTime");
			return (Criteria) this;
		}

		public Criteria andReservationTimeNotEqualTo(String value) {
			addCriterion("reservation_time <>", value, "reservationTime");
			return (Criteria) this;
		}

		public Criteria andReservationTimeGreaterThan(String value) {
			addCriterion("reservation_time >", value, "reservationTime");
			return (Criteria) this;
		}

		public Criteria andReservationTimeGreaterThanOrEqualTo(String value) {
			addCriterion("reservation_time >=", value, "reservationTime");
			return (Criteria) this;
		}

		public Criteria andReservationTimeLessThan(String value) {
			addCriterion("reservation_time <", value, "reservationTime");
			return (Criteria) this;
		}

		public Criteria andReservationTimeLessThanOrEqualTo(String value) {
			addCriterion("reservation_time <=", value, "reservationTime");
			return (Criteria) this;
		}

		public Criteria andReservationTimeLike(String value) {
			addCriterion("reservation_time like", value, "reservationTime");
			return (Criteria) this;
		}

		public Criteria andReservationTimeNotLike(String value) {
			addCriterion("reservation_time not like", value, "reservationTime");
			return (Criteria) this;
		}

		public Criteria andReservationTimeIn(List<String> values) {
			addCriterion("reservation_time in", values, "reservationTime");
			return (Criteria) this;
		}

		public Criteria andReservationTimeNotIn(List<String> values) {
			addCriterion("reservation_time not in", values, "reservationTime");
			return (Criteria) this;
		}

		public Criteria andReservationTimeBetween(String value1, String value2) {
			addCriterion("reservation_time between", value1, value2, "reservationTime");
			return (Criteria) this;
		}

		public Criteria andReservationTimeNotBetween(String value1, String value2) {
			addCriterion("reservation_time not between", value1, value2, "reservationTime");
			return (Criteria) this;
		}

		public Criteria andServiceEstimatedTimeIsNull() {
			addCriterion("service_estimated_time is null");
			return (Criteria) this;
		}

		public Criteria andServiceEstimatedTimeIsNotNull() {
			addCriterion("service_estimated_time is not null");
			return (Criteria) this;
		}

		public Criteria andServiceEstimatedTimeEqualTo(String value) {
			addCriterion("service_estimated_time =", value, "serviceEstimatedTime");
			return (Criteria) this;
		}

		public Criteria andServiceEstimatedTimeNotEqualTo(String value) {
			addCriterion("service_estimated_time <>", value, "serviceEstimatedTime");
			return (Criteria) this;
		}

		public Criteria andServiceEstimatedTimeGreaterThan(String value) {
			addCriterion("service_estimated_time >", value, "serviceEstimatedTime");
			return (Criteria) this;
		}

		public Criteria andServiceEstimatedTimeGreaterThanOrEqualTo(String value) {
			addCriterion("service_estimated_time >=", value, "serviceEstimatedTime");
			return (Criteria) this;
		}

		public Criteria andServiceEstimatedTimeLessThan(String value) {
			addCriterion("service_estimated_time <", value, "serviceEstimatedTime");
			return (Criteria) this;
		}

		public Criteria andServiceEstimatedTimeLessThanOrEqualTo(String value) {
			addCriterion("service_estimated_time <=", value, "serviceEstimatedTime");
			return (Criteria) this;
		}

		public Criteria andServiceEstimatedTimeLike(String value) {
			addCriterion("service_estimated_time like", value, "serviceEstimatedTime");
			return (Criteria) this;
		}

		public Criteria andServiceEstimatedTimeNotLike(String value) {
			addCriterion("service_estimated_time not like", value, "serviceEstimatedTime");
			return (Criteria) this;
		}

		public Criteria andServiceEstimatedTimeIn(List<String> values) {
			addCriterion("service_estimated_time in", values, "serviceEstimatedTime");
			return (Criteria) this;
		}

		public Criteria andServiceEstimatedTimeNotIn(List<String> values) {
			addCriterion("service_estimated_time not in", values, "serviceEstimatedTime");
			return (Criteria) this;
		}

		public Criteria andServiceEstimatedTimeBetween(String value1, String value2) {
			addCriterion("service_estimated_time between", value1, value2, "serviceEstimatedTime");
			return (Criteria) this;
		}

		public Criteria andServiceEstimatedTimeNotBetween(String value1, String value2) {
			addCriterion("service_estimated_time not between", value1, value2, "serviceEstimatedTime");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgIsNull() {
			addCriterion("delete_flg is null");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgIsNotNull() {
			addCriterion("delete_flg is not null");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgEqualTo(Integer value) {
			addCriterion("delete_flg =", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgNotEqualTo(Integer value) {
			addCriterion("delete_flg <>", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgGreaterThan(Integer value) {
			addCriterion("delete_flg >", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgGreaterThanOrEqualTo(Integer value) {
			addCriterion("delete_flg >=", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgLessThan(Integer value) {
			addCriterion("delete_flg <", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgLessThanOrEqualTo(Integer value) {
			addCriterion("delete_flg <=", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgIn(List<Integer> values) {
			addCriterion("delete_flg in", values, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgNotIn(List<Integer> values) {
			addCriterion("delete_flg not in", values, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgBetween(Integer value1, Integer value2) {
			addCriterion("delete_flg between", value1, value2, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgNotBetween(Integer value1, Integer value2) {
			addCriterion("delete_flg not between", value1, value2, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andCustomerPhoneNumberIsNull() {
			addCriterion("customer_phone_number is null");
			return (Criteria) this;
		}

		public Criteria andCustomerPhoneNumberIsNotNull() {
			addCriterion("customer_phone_number is not null");
			return (Criteria) this;
		}

		public Criteria andCustomerPhoneNumberEqualTo(String value) {
			addCriterion("customer_phone_number =", value, "customerPhoneNumber");
			return (Criteria) this;
		}

		public Criteria andCustomerPhoneNumberNotEqualTo(String value) {
			addCriterion("customer_phone_number <>", value, "customerPhoneNumber");
			return (Criteria) this;
		}

		public Criteria andCustomerPhoneNumberGreaterThan(String value) {
			addCriterion("customer_phone_number >", value, "customerPhoneNumber");
			return (Criteria) this;
		}

		public Criteria andCustomerPhoneNumberGreaterThanOrEqualTo(String value) {
			addCriterion("customer_phone_number >=", value, "customerPhoneNumber");
			return (Criteria) this;
		}

		public Criteria andCustomerPhoneNumberLessThan(String value) {
			addCriterion("customer_phone_number <", value, "customerPhoneNumber");
			return (Criteria) this;
		}

		public Criteria andCustomerPhoneNumberLessThanOrEqualTo(String value) {
			addCriterion("customer_phone_number <=", value, "customerPhoneNumber");
			return (Criteria) this;
		}

		public Criteria andCustomerPhoneNumberLike(String value) {
			addCriterion("customer_phone_number like", value, "customerPhoneNumber");
			return (Criteria) this;
		}

		public Criteria andCustomerPhoneNumberNotLike(String value) {
			addCriterion("customer_phone_number not like", value, "customerPhoneNumber");
			return (Criteria) this;
		}

		public Criteria andCustomerPhoneNumberIn(List<String> values) {
			addCriterion("customer_phone_number in", values, "customerPhoneNumber");
			return (Criteria) this;
		}

		public Criteria andCustomerPhoneNumberNotIn(List<String> values) {
			addCriterion("customer_phone_number not in", values, "customerPhoneNumber");
			return (Criteria) this;
		}

		public Criteria andCustomerPhoneNumberBetween(String value1, String value2) {
			addCriterion("customer_phone_number between", value1, value2, "customerPhoneNumber");
			return (Criteria) this;
		}

		public Criteria andCustomerPhoneNumberNotBetween(String value1, String value2) {
			addCriterion("customer_phone_number not between", value1, value2, "customerPhoneNumber");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table reservationhistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table reservationhistory
     *
     * @mbg.generated do_not_delete_during_merge Thu Nov 05 14:48:29 KST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}