package com.dreamhanks.HappyBeautyManager.dto;

import java.util.Date;

public class ReservationCustomerstamp {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_customerstamp.reservation_customerstamp_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer reservationCustomerstampId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_customerstamp.manager_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String managerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_customerstamp.reservation_delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer reservationDeleteFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_customerstamp.judgment_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer judgmentFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_customerstamp.resarvation_create_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Date resarvationCreateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_customerstamp.id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_customerstamp.owner_phone_number
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String ownerPhoneNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_customerstamp.customer_phone_number
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String customerPhoneNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_customerstamp.stamp_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer stampId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_customerstamp.customer_qr_text
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String customerQrText;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_customerstamp.stamp_count
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer stampCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_customerstamp.delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Boolean deleteFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_customerstamp.validity_start_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Date validityStartDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_customerstamp.validity_end_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Date validityEndDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_customerstamp.update_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_customerstamp.create_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Date createDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_customerstamp.reservation_customerstamp_id
	 * @return  the value of reservation_customerstamp.reservation_customerstamp_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getReservationCustomerstampId() {
		return reservationCustomerstampId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_customerstamp.reservation_customerstamp_id
	 * @param reservationCustomerstampId  the value for reservation_customerstamp.reservation_customerstamp_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setReservationCustomerstampId(Integer reservationCustomerstampId) {
		this.reservationCustomerstampId = reservationCustomerstampId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_customerstamp.manager_id
	 * @return  the value of reservation_customerstamp.manager_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getManagerId() {
		return managerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_customerstamp.manager_id
	 * @param managerId  the value for reservation_customerstamp.manager_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setManagerId(String managerId) {
		this.managerId = managerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_customerstamp.reservation_delete_flg
	 * @return  the value of reservation_customerstamp.reservation_delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getReservationDeleteFlg() {
		return reservationDeleteFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_customerstamp.reservation_delete_flg
	 * @param reservationDeleteFlg  the value for reservation_customerstamp.reservation_delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setReservationDeleteFlg(Integer reservationDeleteFlg) {
		this.reservationDeleteFlg = reservationDeleteFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_customerstamp.judgment_flg
	 * @return  the value of reservation_customerstamp.judgment_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getJudgmentFlg() {
		return judgmentFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_customerstamp.judgment_flg
	 * @param judgmentFlg  the value for reservation_customerstamp.judgment_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setJudgmentFlg(Integer judgmentFlg) {
		this.judgmentFlg = judgmentFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_customerstamp.resarvation_create_date
	 * @return  the value of reservation_customerstamp.resarvation_create_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Date getResarvationCreateDate() {
		return resarvationCreateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_customerstamp.resarvation_create_date
	 * @param resarvationCreateDate  the value for reservation_customerstamp.resarvation_create_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setResarvationCreateDate(Date resarvationCreateDate) {
		this.resarvationCreateDate = resarvationCreateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_customerstamp.id
	 * @return  the value of reservation_customerstamp.id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_customerstamp.id
	 * @param id  the value for reservation_customerstamp.id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_customerstamp.owner_phone_number
	 * @return  the value of reservation_customerstamp.owner_phone_number
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getOwnerPhoneNumber() {
		return ownerPhoneNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_customerstamp.owner_phone_number
	 * @param ownerPhoneNumber  the value for reservation_customerstamp.owner_phone_number
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setOwnerPhoneNumber(String ownerPhoneNumber) {
		this.ownerPhoneNumber = ownerPhoneNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_customerstamp.customer_phone_number
	 * @return  the value of reservation_customerstamp.customer_phone_number
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getCustomerPhoneNumber() {
		return customerPhoneNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_customerstamp.customer_phone_number
	 * @param customerPhoneNumber  the value for reservation_customerstamp.customer_phone_number
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setCustomerPhoneNumber(String customerPhoneNumber) {
		this.customerPhoneNumber = customerPhoneNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_customerstamp.stamp_id
	 * @return  the value of reservation_customerstamp.stamp_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getStampId() {
		return stampId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_customerstamp.stamp_id
	 * @param stampId  the value for reservation_customerstamp.stamp_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setStampId(Integer stampId) {
		this.stampId = stampId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_customerstamp.customer_qr_text
	 * @return  the value of reservation_customerstamp.customer_qr_text
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getCustomerQrText() {
		return customerQrText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_customerstamp.customer_qr_text
	 * @param customerQrText  the value for reservation_customerstamp.customer_qr_text
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setCustomerQrText(String customerQrText) {
		this.customerQrText = customerQrText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_customerstamp.stamp_count
	 * @return  the value of reservation_customerstamp.stamp_count
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getStampCount() {
		return stampCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_customerstamp.stamp_count
	 * @param stampCount  the value for reservation_customerstamp.stamp_count
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setStampCount(Integer stampCount) {
		this.stampCount = stampCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_customerstamp.delete_flg
	 * @return  the value of reservation_customerstamp.delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Boolean getDeleteFlg() {
		return deleteFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_customerstamp.delete_flg
	 * @param deleteFlg  the value for reservation_customerstamp.delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setDeleteFlg(Boolean deleteFlg) {
		this.deleteFlg = deleteFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_customerstamp.validity_start_date
	 * @return  the value of reservation_customerstamp.validity_start_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Date getValidityStartDate() {
		return validityStartDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_customerstamp.validity_start_date
	 * @param validityStartDate  the value for reservation_customerstamp.validity_start_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setValidityStartDate(Date validityStartDate) {
		this.validityStartDate = validityStartDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_customerstamp.validity_end_date
	 * @return  the value of reservation_customerstamp.validity_end_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Date getValidityEndDate() {
		return validityEndDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_customerstamp.validity_end_date
	 * @param validityEndDate  the value for reservation_customerstamp.validity_end_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setValidityEndDate(Date validityEndDate) {
		this.validityEndDate = validityEndDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_customerstamp.update_date
	 * @return  the value of reservation_customerstamp.update_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_customerstamp.update_date
	 * @param updateDate  the value for reservation_customerstamp.update_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_customerstamp.create_date
	 * @return  the value of reservation_customerstamp.create_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_customerstamp.create_date
	 * @param createDate  the value for reservation_customerstamp.create_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
}