package com.dreamhanks.HappyBeautyManager.dao;

import com.dreamhanks.HappyBeautyManager.dto.Manager;
import com.dreamhanks.HappyBeautyManager.dto.ManagerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ManagerMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table manager
     * @mbg.generated  Tue Nov 17 15:08:29 JST 2020
     */
    long countByExample(ManagerExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table manager
     * @mbg.generated  Tue Nov 17 15:08:29 JST 2020
     */
    int deleteByExample(ManagerExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table manager
     * @mbg.generated  Tue Nov 17 15:08:29 JST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table manager
     * @mbg.generated  Tue Nov 17 15:08:29 JST 2020
     */
    int insert(Manager record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table manager
     * @mbg.generated  Tue Nov 17 15:08:29 JST 2020
     */
    int insertSelective(Manager record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table manager
     * @mbg.generated  Tue Nov 17 15:08:29 JST 2020
     */
    List<Manager> selectByExample(ManagerExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table manager
     * @mbg.generated  Tue Nov 17 15:08:29 JST 2020
     */
    Manager selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table manager
     * @mbg.generated  Tue Nov 17 15:08:29 JST 2020
     */
    int updateByExampleSelective(@Param("record") Manager record,
            @Param("example") ManagerExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table manager
     * @mbg.generated  Tue Nov 17 15:08:29 JST 2020
     */
    int updateByExample(@Param("record") Manager record, @Param("example") ManagerExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table manager
     * @mbg.generated  Tue Nov 17 15:08:29 JST 2020
     */
    int updateByPrimaryKeySelective(Manager record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table manager
     * @mbg.generated  Tue Nov 17 15:08:29 JST 2020
     */
    int updateByPrimaryKey(Manager record);
}