package com.dreamhanks.HappyBeautyManager.dao;

import com.dreamhanks.HappyBeautyManager.dto.ReservationChargehistory;
import com.dreamhanks.HappyBeautyManager.dto.ReservationChargehistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReservationChargehistoryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_chargehistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	long countByExample(ReservationChargehistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_chargehistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int deleteByExample(ReservationChargehistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_chargehistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int deleteByPrimaryKey(Integer reservationChargehistoryId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_chargehistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int insert(ReservationChargehistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_chargehistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int insertSelective(ReservationChargehistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_chargehistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	List<ReservationChargehistory> selectByExample(ReservationChargehistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_chargehistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	ReservationChargehistory selectByPrimaryKey(Integer reservationChargehistoryId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_chargehistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int updateByExampleSelective(@Param("record") ReservationChargehistory record,
			@Param("example") ReservationChargehistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_chargehistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int updateByExample(@Param("record") ReservationChargehistory record,
			@Param("example") ReservationChargehistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_chargehistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int updateByPrimaryKeySelective(ReservationChargehistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_chargehistory
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int updateByPrimaryKey(ReservationChargehistory record);
}