package com.dreamhanks.HappyBeautyManager.dao;

import com.dreamhanks.HappyBeautyManager.dto.ReservationOwner;
import com.dreamhanks.HappyBeautyManager.dto.ReservationOwnerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReservationOwnerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_owner
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	long countByExample(ReservationOwnerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_owner
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int deleteByExample(ReservationOwnerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_owner
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int deleteByPrimaryKey(Integer reservationOwnerId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_owner
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int insert(ReservationOwner record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_owner
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int insertSelective(ReservationOwner record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_owner
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	List<ReservationOwner> selectByExample(ReservationOwnerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_owner
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	ReservationOwner selectByPrimaryKey(Integer reservationOwnerId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_owner
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int updateByExampleSelective(@Param("record") ReservationOwner record,
			@Param("example") ReservationOwnerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_owner
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int updateByExample(@Param("record") ReservationOwner record, @Param("example") ReservationOwnerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_owner
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int updateByPrimaryKeySelective(ReservationOwner record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reservation_owner
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	int updateByPrimaryKey(ReservationOwner record);
}