package com.dreamhanks.HappyBeautyManager.dao;

import com.dreamhanks.HappyBeautyManager.dto.SearchDisplayMaster;
import com.dreamhanks.HappyBeautyManager.dto.SearchDisplayMasterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SearchDisplayMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_display_master
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    long countByExample(SearchDisplayMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_display_master
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    int deleteByExample(SearchDisplayMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_display_master
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_display_master
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    int insert(SearchDisplayMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_display_master
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    int insertSelective(SearchDisplayMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_display_master
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    List<SearchDisplayMaster> selectByExample(SearchDisplayMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_display_master
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    SearchDisplayMaster selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_display_master
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    int updateByExampleSelective(@Param("record") SearchDisplayMaster record, @Param("example") SearchDisplayMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_display_master
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    int updateByExample(@Param("record") SearchDisplayMaster record, @Param("example") SearchDisplayMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_display_master
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    int updateByPrimaryKeySelective(SearchDisplayMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_display_master
     *
     * @mbg.generated Thu Nov 19 15:40:16 KST 2020
     */
    int updateByPrimaryKey(SearchDisplayMaster record);
}