package com.dreamhanks.HappyBeautyManager.dto;

import java.util.Date;

public class ReservationStamp {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_stamp.reservation_stamp_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer reservationStampId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_stamp.manager_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String managerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_stamp.reservation_delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer reservationDeleteFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_stamp.judgment_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer judgmentFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_stamp.resarvation_create_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Date resarvationCreateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_stamp.id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_stamp.owner_phone_number
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String ownerPhoneNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_stamp.stamp_qr_text
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String stampQrText;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_stamp.stamp_name
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String stampName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_stamp.stamp_row
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer stampRow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_stamp.stamp_col
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer stampCol;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_stamp.stamp_img
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String stampImg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_stamp.stamp_back_img
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String stampBackImg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_stamp.validity_start_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Date validityStartDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_stamp.validity_end_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Date validityEndDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_stamp.validity_plus_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer validityPlusDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_stamp.validity_plus_type
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer validityPlusType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_stamp.validity_type
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer validityType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_stamp.delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Boolean deleteFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_stamp.create_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_stamp.stamp_theme
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private Integer stampTheme;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reservation_stamp.stamp_contents
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	private String stampContents;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_stamp.reservation_stamp_id
	 * @return  the value of reservation_stamp.reservation_stamp_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getReservationStampId() {
		return reservationStampId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_stamp.reservation_stamp_id
	 * @param reservationStampId  the value for reservation_stamp.reservation_stamp_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setReservationStampId(Integer reservationStampId) {
		this.reservationStampId = reservationStampId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_stamp.manager_id
	 * @return  the value of reservation_stamp.manager_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getManagerId() {
		return managerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_stamp.manager_id
	 * @param managerId  the value for reservation_stamp.manager_id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setManagerId(String managerId) {
		this.managerId = managerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_stamp.reservation_delete_flg
	 * @return  the value of reservation_stamp.reservation_delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getReservationDeleteFlg() {
		return reservationDeleteFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_stamp.reservation_delete_flg
	 * @param reservationDeleteFlg  the value for reservation_stamp.reservation_delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setReservationDeleteFlg(Integer reservationDeleteFlg) {
		this.reservationDeleteFlg = reservationDeleteFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_stamp.judgment_flg
	 * @return  the value of reservation_stamp.judgment_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getJudgmentFlg() {
		return judgmentFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_stamp.judgment_flg
	 * @param judgmentFlg  the value for reservation_stamp.judgment_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setJudgmentFlg(Integer judgmentFlg) {
		this.judgmentFlg = judgmentFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_stamp.resarvation_create_date
	 * @return  the value of reservation_stamp.resarvation_create_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Date getResarvationCreateDate() {
		return resarvationCreateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_stamp.resarvation_create_date
	 * @param resarvationCreateDate  the value for reservation_stamp.resarvation_create_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setResarvationCreateDate(Date resarvationCreateDate) {
		this.resarvationCreateDate = resarvationCreateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_stamp.id
	 * @return  the value of reservation_stamp.id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_stamp.id
	 * @param id  the value for reservation_stamp.id
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_stamp.owner_phone_number
	 * @return  the value of reservation_stamp.owner_phone_number
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getOwnerPhoneNumber() {
		return ownerPhoneNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_stamp.owner_phone_number
	 * @param ownerPhoneNumber  the value for reservation_stamp.owner_phone_number
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setOwnerPhoneNumber(String ownerPhoneNumber) {
		this.ownerPhoneNumber = ownerPhoneNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_stamp.stamp_qr_text
	 * @return  the value of reservation_stamp.stamp_qr_text
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getStampQrText() {
		return stampQrText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_stamp.stamp_qr_text
	 * @param stampQrText  the value for reservation_stamp.stamp_qr_text
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setStampQrText(String stampQrText) {
		this.stampQrText = stampQrText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_stamp.stamp_name
	 * @return  the value of reservation_stamp.stamp_name
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getStampName() {
		return stampName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_stamp.stamp_name
	 * @param stampName  the value for reservation_stamp.stamp_name
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setStampName(String stampName) {
		this.stampName = stampName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_stamp.stamp_row
	 * @return  the value of reservation_stamp.stamp_row
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getStampRow() {
		return stampRow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_stamp.stamp_row
	 * @param stampRow  the value for reservation_stamp.stamp_row
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setStampRow(Integer stampRow) {
		this.stampRow = stampRow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_stamp.stamp_col
	 * @return  the value of reservation_stamp.stamp_col
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getStampCol() {
		return stampCol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_stamp.stamp_col
	 * @param stampCol  the value for reservation_stamp.stamp_col
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setStampCol(Integer stampCol) {
		this.stampCol = stampCol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_stamp.stamp_img
	 * @return  the value of reservation_stamp.stamp_img
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getStampImg() {
		return stampImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_stamp.stamp_img
	 * @param stampImg  the value for reservation_stamp.stamp_img
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setStampImg(String stampImg) {
		this.stampImg = stampImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_stamp.stamp_back_img
	 * @return  the value of reservation_stamp.stamp_back_img
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getStampBackImg() {
		return stampBackImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_stamp.stamp_back_img
	 * @param stampBackImg  the value for reservation_stamp.stamp_back_img
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setStampBackImg(String stampBackImg) {
		this.stampBackImg = stampBackImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_stamp.validity_start_date
	 * @return  the value of reservation_stamp.validity_start_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Date getValidityStartDate() {
		return validityStartDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_stamp.validity_start_date
	 * @param validityStartDate  the value for reservation_stamp.validity_start_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setValidityStartDate(Date validityStartDate) {
		this.validityStartDate = validityStartDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_stamp.validity_end_date
	 * @return  the value of reservation_stamp.validity_end_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Date getValidityEndDate() {
		return validityEndDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_stamp.validity_end_date
	 * @param validityEndDate  the value for reservation_stamp.validity_end_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setValidityEndDate(Date validityEndDate) {
		this.validityEndDate = validityEndDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_stamp.validity_plus_date
	 * @return  the value of reservation_stamp.validity_plus_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getValidityPlusDate() {
		return validityPlusDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_stamp.validity_plus_date
	 * @param validityPlusDate  the value for reservation_stamp.validity_plus_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setValidityPlusDate(Integer validityPlusDate) {
		this.validityPlusDate = validityPlusDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_stamp.validity_plus_type
	 * @return  the value of reservation_stamp.validity_plus_type
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getValidityPlusType() {
		return validityPlusType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_stamp.validity_plus_type
	 * @param validityPlusType  the value for reservation_stamp.validity_plus_type
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setValidityPlusType(Integer validityPlusType) {
		this.validityPlusType = validityPlusType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_stamp.validity_type
	 * @return  the value of reservation_stamp.validity_type
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getValidityType() {
		return validityType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_stamp.validity_type
	 * @param validityType  the value for reservation_stamp.validity_type
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setValidityType(Integer validityType) {
		this.validityType = validityType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_stamp.delete_flg
	 * @return  the value of reservation_stamp.delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Boolean getDeleteFlg() {
		return deleteFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_stamp.delete_flg
	 * @param deleteFlg  the value for reservation_stamp.delete_flg
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setDeleteFlg(Boolean deleteFlg) {
		this.deleteFlg = deleteFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_stamp.create_date
	 * @return  the value of reservation_stamp.create_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_stamp.create_date
	 * @param createDate  the value for reservation_stamp.create_date
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_stamp.stamp_theme
	 * @return  the value of reservation_stamp.stamp_theme
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public Integer getStampTheme() {
		return stampTheme;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_stamp.stamp_theme
	 * @param stampTheme  the value for reservation_stamp.stamp_theme
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setStampTheme(Integer stampTheme) {
		this.stampTheme = stampTheme;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reservation_stamp.stamp_contents
	 * @return  the value of reservation_stamp.stamp_contents
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public String getStampContents() {
		return stampContents;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reservation_stamp.stamp_contents
	 * @param stampContents  the value for reservation_stamp.stamp_contents
	 * @mbg.generated  Mon Nov 16 16:42:54 KST 2020
	 */
	public void setStampContents(String stampContents) {
		this.stampContents = stampContents;
	}
}