package com.dreamhanks.searchborad.dao;

import com.dreamhanks.searchborad.dto.Borad;
import com.dreamhanks.searchborad.dto.BoradExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BoradMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table borad
	 * @mbg.generated  Fri Oct 02 15:52:36 JST 2020
	 */
	long countByExample(BoradExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table borad
	 * @mbg.generated  Fri Oct 02 15:52:36 JST 2020
	 */
	int deleteByExample(BoradExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table borad
	 * @mbg.generated  Fri Oct 02 15:52:36 JST 2020
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table borad
	 * @mbg.generated  Fri Oct 02 15:52:36 JST 2020
	 */
	int insert(Borad record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table borad
	 * @mbg.generated  Fri Oct 02 15:52:36 JST 2020
	 */
	int insertSelective(Borad record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table borad
	 * @mbg.generated  Fri Oct 02 15:52:36 JST 2020
	 */
	List<Borad> selectByExample(BoradExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table borad
	 * @mbg.generated  Fri Oct 02 15:52:36 JST 2020
	 */
	Borad selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table borad
	 * @mbg.generated  Fri Oct 02 15:52:36 JST 2020
	 */
	int updateByExampleSelective(@Param("record") Borad record, @Param("example") BoradExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table borad
	 * @mbg.generated  Fri Oct 02 15:52:36 JST 2020
	 */
	int updateByExample(@Param("record") Borad record, @Param("example") BoradExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table borad
	 * @mbg.generated  Fri Oct 02 15:52:36 JST 2020
	 */
	int updateByPrimaryKeySelective(Borad record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table borad
	 * @mbg.generated  Fri Oct 02 15:52:36 JST 2020
	 */
	int updateByPrimaryKey(Borad record);
}